// UIL Spelling & Vocabulary Practice - Reference Data
// Prefixes, suffixes, practice tests, and word analysis

// Common prefixes with meanings for analysis
const PREFIXES = {
  "a-": "not, without",
  "ab-": "away from",
  "ad-": "toward, to",
  "aero-": "air",
  "agro-": "field, agriculture",
  "alpha-": "first",
  "an-": "not, without",
  "ana-": "up, back, again",
  "ante-": "before",
  "anti-": "against, opposite",
  "auto-": "self",
  "bi-": "two",
  "bio-": "life",
  "cata-": "down",
  "centi-": "hundred",
  "circum-": "around",
  "co-": "together, with",
  "com-": "together, with",
  "con-": "together, with",
  "contra-": "against",
  "counter-": "against",
  "de-": "down, from, reverse",
  "deca-": "ten",
  "demi-": "half",
  "di-": "two",
  "dia-": "through, across",
  "dis-": "not, apart",
  "dys-": "bad, difficult",
  "eco-": "environment",
  "em-": "in, into",
  "en-": "in, into, cause",
  "endo-": "within",
  "epi-": "upon, above",
  "equi-": "equal",
  "eu-": "good, well",
  "ex-": "out of, former",
  "exo-": "outside",
  "extra-": "beyond",
  "fore-": "before, front",
  "geo-": "earth",
  "hemi-": "half",
  "hetero-": "different",
  "homo-": "same",
  "hydro-": "water",
  "hyper-": "over, excessive",
  "hypo-": "under, below",
  "il-": "not",
  "im-": "not, into",
  "in-": "not, into",
  "infra-": "below",
  "inter-": "between, among",
  "intra-": "within",
  "ir-": "not",
  "iso-": "equal",
  "macro-": "large",
  "mal-": "bad",
  "mega-": "large, great",
  "meta-": "beyond, change",
  "micro-": "small",
  "mid-": "middle",
  "milli-": "thousand",
  "mini-": "small",
  "mis-": "wrong, bad",
  "mono-": "one, single",
  "multi-": "many",
  "neo-": "new",
  "neuro-": "nerve",
  "non-": "not",
  "ob-": "against",
  "omni-": "all",
  "over-": "excessive",
  "paleo-": "ancient",
  "pan-": "all",
  "para-": "beside, beyond",
  "peri-": "around",
  "photo-": "light",
  "poly-": "many",
  "post-": "after",
  "pre-": "before",
  "pro-": "forward, in favor",
  "proto-": "first",
  "pseudo-": "false",
  "psycho-": "mind",
  "quadr-": "four",
  "quasi-": "seemingly",
  "re-": "again, back",
  "retro-": "backward",
  "sacro-": "sacred",
  "self-": "self",
  "semi-": "half, partly",
  "sub-": "under, below",
  "super-": "above, beyond",
  "supra-": "above",
  "sym-": "together",
  "syn-": "together",
  "tele-": "far, distant",
  "trans-": "across, beyond",
  "tri-": "three",
  "ultra-": "beyond, extreme",
  "un-": "not, reverse",
  "under-": "below, less",
  "uni-": "one",
  "vice-": "in place of"
};

// Common suffixes with meanings
const SUFFIXES = {
  "-able": "capable of being",
  "-ible": "capable of being",
  "-aceous": "resembling, relating to",
  "-acious": "having quality of",
  "-acity": "quality of",
  "-ade": "action, product",
  "-age": "action, state",
  "-al": "relating to",
  "-an": "relating to, native of",
  "-ance": "state, quality",
  "-ancy": "state, quality",
  "-ant": "one who, performing",
  "-ar": "relating to",
  "-arian": "one who, believer in",
  "-ary": "relating to, place for",
  "-ate": "having, cause to be",
  "-ation": "action, process",
  "-ative": "tending to",
  "-cide": "killing",
  "-cracy": "rule, government",
  "-crat": "ruler",
  "-dom": "state, realm",
  "-ean": "relating to",
  "-ectomy": "surgical removal",
  "-ee": "one who receives",
  "-emia": "blood condition",
  "-ence": "state, quality",
  "-ency": "state, quality",
  "-ent": "performing, causing",
  "-eous": "having nature of",
  "-er": "one who, more",
  "-ery": "place, practice",
  "-escence": "becoming",
  "-escent": "becoming",
  "-esque": "in the style of",
  "-ess": "female",
  "-est": "most",
  "-etic": "relating to",
  "-ette": "small, feminine",
  "-eur": "one who",
  "-ful": "full of",
  "-fy": "make, cause",
  "-gamy": "marriage",
  "-genic": "producing",
  "-geny": "origin, production",
  "-gon": "angle",
  "-gram": "written, drawn",
  "-graph": "writing, instrument",
  "-graphy": "writing, description",
  "-ia": "condition, region",
  "-ial": "relating to",
  "-ian": "relating to, one who",
  "-iasis": "disease condition",
  "-iatric": "medical treatment",
  "-ible": "capable of",
  "-ic": "relating to",
  "-ical": "relating to",
  "-ician": "specialist",
  "-ics": "science, study",
  "-id": "having quality of",
  "-ify": "make, cause to be",
  "-ile": "capable of, relating to",
  "-ine": "relating to, resembling",
  "-ion": "action, condition",
  "-ious": "having quality of",
  "-ism": "doctrine, practice",
  "-ist": "one who practices",
  "-istic": "relating to",
  "-ite": "native, follower",
  "-itis": "inflammation",
  "-itude": "state, quality",
  "-ity": "state, quality",
  "-ive": "tending to, having nature of",
  "-ization": "process of making",
  "-ize": "make, cause to be",
  "-kinesis": "movement",
  "-less": "without",
  "-like": "resembling",
  "-ling": "small, young",
  "-logy": "study of",
  "-ly": "in manner of",
  "-mania": "obsession",
  "-ment": "action, result",
  "-meter": "measuring device",
  "-metry": "measurement",
  "-morph": "form, shape",
  "-ness": "state, quality",
  "-nomy": "system of laws",
  "-oid": "resembling",
  "-ology": "study of",
  "-oma": "tumor, mass",
  "-opia": "vision condition",
  "-or": "one who",
  "-ory": "place for, relating to",
  "-osis": "condition, process",
  "-ous": "full of, having",
  "-pathy": "feeling, disease",
  "-phage": "eating",
  "-phagy": "eating",
  "-phile": "loving",
  "-philia": "love of",
  "-phobia": "fear of",
  "-phone": "sound",
  "-phyte": "plant",
  "-plasm": "formed substance",
  "-plasty": "surgical repair",
  "-pod": "foot",
  "-scope": "viewing instrument",
  "-scopy": "viewing",
  "-ship": "state, office",
  "-sis": "condition, process",
  "-some": "characterized by",
  "-stasis": "standing, stopping",
  "-tion": "action, state",
  "-tomy": "cutting",
  "-tude": "state, quality",
  "-ular": "relating to",
  "-ulent": "full of",
  "-ure": "action, process",
  "-ward": "direction",
  "-wise": "manner",
  "-y": "characterized by"
};

// Practice test data from pronouncer keys
const PRACTICE_TESTS = {
  "meet1": {
    name: "Virtual Challenge Meet #1",
    audio: {
      "words1-40": "audio/meet1-words-1-40.mp3",
      "words41-70": "audio/meet1-words-41-70.mp3",
      "tiebreaker": "audio/meet1-tiebreaker-1-20.mp3"
    },
    words: [
      {word:"pediatrician",def:"a doctor who treats infants and children"},
      {word:"xenophile",def:"a person to whom foreign people and cultures are appealing"},
      {word:"genome",def:"an organism's hereditary material found in chromosomes, DNA, or RNA"},
      {word:"Eucalyptus",def:"a genus of trees"},
      {word:"cronyism",def:"showing friends or relatives special favor by appointing them to positions for which they are not qualified"},
      {word:"quintessential",def:"typical",outside:true},
      {word:"adroit",def:"dexterous; skillful"},
      {word:"consentaneous",def:"being in agreement"},
      {word:"toque",def:"a kind of hat or cap",outside:true},
      {word:"faun",def:"Roman Mythology. a mythological deity which is part man and part animal"},
      {word:"gurney",def:"a stretcher used to transport patients"},
      {word:"oxycephaly",def:"an abnormality in which the top of the head is pointed"},
      {word:"non prosequitur",def:"Law. a term indicating the judgment which is entered against someone who fails to appear in court to pursue a suit"},
      {word:"akaryocyte",def:"a cell which has no nucleus"},
      {word:"saute",def:"(v.) to fry briefly | (n.) food prepared in such a way"},
      {word:"chi-square",def:"a term used in statistics"},
      {word:"pyriform",def:"in the shape of a pear"},
      {word:"nolo contendere",def:"Law. a plea made by an accused which acknowledges guilt",outside:true},
      {word:"encroachment",def:"the act of advancing past limitations of rights or property; a type of football violation"},
      {word:"bangkok",def:"a kind of hat"},
      {word:"politesse",def:"the act of being courteous"},
      {word:"chancellor",def:"a high ranking official"},
      {word:"vesicate",def:"to blister"},
      {word:"arrhythmia",def:"a disturbance in the pattern and regularity of the heartbeat",outside:true},
      {word:"dictum",def:"a pronouncement; Law. a judge's opinion that is not binding"},
      {word:"Bauhaus",def:"having to do with a school of design"},
      {word:"penuche",def:"a confection made with brown sugar, milk, and nuts",alt:"penuchi"},
      {word:"multivoltine",def:"producing offspring several times in the same season"},
      {word:"theocentric",def:"placing God as the focal point"},
      {word:"irascible",def:"short-tempered",outside:true},
      {word:"scansorial",def:"Zoology. adapted for climbing"},
      {word:"ostensibly",def:"in a manner that is outward or apparent"},
      {word:"nevus",def:"a birthmark or mole",outside:true},
      {word:"algorism",def:"the Arabic system of numerals; computation using such numerals"},
      {word:"vaporescence",def:"the formation of something such as fog, mist, steam, etc."},
      {word:"spinescent",def:"having bristles; ending in a bristle"},
      {word:"granulocyte",def:"a kind of white blood cell"},
      {word:"dhurrie",def:"a kind of rug made in India",outside:true},
      {word:"esophagus",def:"the part of the body through which food passes to the stomach",alt:"oesophagus"},
      {word:"lotus position",def:"a way of sitting used in yoga"},
      {word:"equilibrate",def:"to bring into balance"},
      {word:"youngberry",def:"a type of shrub; the fruit produced by this shrub"},
      {word:"henbane",def:"a kind of poisonous plant",outside:true},
      {word:"geophagy",def:"the eating of something such as clay or chalk"},
      {word:"attache case",def:"a slim container with hinges and a lock which is usually used to carry papers, books, etc.",outside:true},
      {word:"laetrile",def:"a substance sourced from amygdalin"},
      {word:"transitionary",def:"having to do with change or movement from one point to another"},
      {word:"gravitas",def:"seriousness of manner or conduct"},
      {word:"agouti",def:"a type of burrowing rodent; a type of grizzled fur"},
      {word:"gimmal",def:"a kind of ring; a device used in a clock"}
    ]
  },
  "meet2": {
    name: "Virtual Challenge Meet #2",
    audio: {
      "words1-40": "audio/meet2-words-1-40.mp3",
      "words41-70": "audio/meet2-words-41-70.mp3",
      "tiebreaker": "audio/meet2-tiebreaker-1-20.mp3"
    },
    words: [
      {word:"escarole",def:"a kind of endive"},
      {word:"Diogenes",def:"a Greek philosopher"},
      {word:"etymon",def:"an earlier version of a word that is the source for the derivative"},
      {word:"labret",def:"an ornament for a lip piercing"},
      {word:"Islamabad",def:"a city in Pakistan"},
      {word:"rubefacient",def:"(adj.) causing the skin to turn red | (n.) a substance that causes the skin to turn red"},
      {word:"arriere-pensee",def:"a reservation usually about the legitimacy of something"},
      {word:"spaceborne",def:"operating in the region beyond the atmosphere of Earth",outside:true},
      {word:"soubrette",def:"a character in a comedy or an opera; the person who plays such a part; a flirtatious woman"},
      {word:"Cinco de Mayo",def:"a day celebrated in some places as a commemoration of the defeat of French troops in 1862"},
      {word:"lyrebird",def:"a kind of feathered vertebrate"},
      {word:"antithesis",def:"a contrast; the exact opposite; a figure of speech"},
      {word:"Judea",def:"a region in the Middle East",alt:"Judaea"},
      {word:"demagoguery",def:"rabble rousing, agitation, or provocation"},
      {word:"ghoulish",def:"like a fiend or devil",outside:true},
      {word:"acoustooptics",def:"a science involving sound and sight"},
      {word:"bergamot",def:"a citrus plant; the oil from this plant"},
      {word:"chambered nautilus",def:"a type of mollusk"},
      {word:"Gouda",def:"a kind of cheese"},
      {word:"affenpinscher",def:"a breed of dogs",outside:true},
      {word:"cabaret",def:"a kind of nightclub that has performances; the show presented in such a nightclub"},
      {word:"Hippocrene",def:"Greek Mythology. a fountain which was believed to be a source of poetic inspiration"},
      {word:"tarboosh",def:"a kind of cap",alt:"tarbush"},
      {word:"leachate",def:"the solution or product resulting from water percolating through soil"},
      {word:"daedal",def:"intricate; artistic"},
      {word:"gyre",def:"(n.) a form that is spiral or circular; a motion that is spiral or circular | (v.) to spiral or whirl",outside:true},
      {word:"oleic acid",def:"an oily liquid used in making soap"},
      {word:"sericeous",def:"silky; Botany. covered with hairs that are like silk"},
      {word:"Beirut",def:"a city in Lebanon",outside:true},
      {word:"kegler",def:"Sports. a person who engages in bowling"},
      {word:"saxophone",def:"Music. a kind of instrument"},
      {word:"Gaelic",def:"having to do with people from Scotland, Ireland, or the Isle of Man who speak a certain language",outside:true},
      {word:"tempera",def:"a substance used in painting; a painting done with such a substance"},
      {word:"Havasupai",def:"a Native American people; a member of this group of people; the language spoken by this group of people"},
      {word:"maitre d'hotel",def:"the person in charge of the dining room staff in a restaurant; a steward or butler; a sauce"},
      {word:"cantonment",def:"the quartering of troops or the quarters for such troops; a military base in India"},
      {word:"punctilio",def:"a nicety or fine point related to etiquette; close adherence to formality"},
      {word:"radicchio",def:"a kind of plant"},
      {word:"U-boat",def:"a German naval submarine",outside:true},
      {word:"Gettysburg",def:"a town in Pennsylvania and the site of a Civil War battle"},
      {word:"coequal",def:"(adj.) being the same as another in size or rank | (n.) one who has the same value or quality as another"},
      {word:"heptathlon",def:"Sports. a contest that has seven events"},
      {word:"shalom",def:"(interjection) an expression used as a greeting or farewell by Jewish people"},
      {word:"rhonchus",def:"a sound similar to snoring caused by bronchial secretions"},
      {word:"metopic",def:"having to do with the forehead",outside:true},
      {word:"adversarial",def:"characteristic of an opponent"},
      {word:"paleozoology",def:"the branch of science that studies animal fossils and ancient animal life"},
      {word:"cliquish",def:"exclusive; partisan",outside:true},
      {word:"daiquiri",def:"a kind of drink"},
      {word:"chemurgy",def:"the development of new products often from agricultural materials"},
      {word:"otolaryngology",def:"a branch of medicine dealing with diseases affecting the ear, nose, and throat",outside:true},
      {word:"rapprochement",def:"the act of reestablishing good relations; reconciliation"},
      {word:"quadrennium",def:"a period of four years"},
      {word:"Naugahyde",def:"a trademark used for a kind of artificial leather"},
      {word:"heroic verse",def:"a form used in poetry"},
      {word:"melliferous",def:"such that it forms or bears honey"},
      {word:"lycanthropy",def:"in folklore, the ability to take on the characteristics and form of a wolf"},
      {word:"nine days' wonder",def:"something which happens and creates a sensation that lasts only for a short time"},
      {word:"postiche",def:"a sham; a toupee"},
      {word:"soliloquy",def:"a literary form in which one person speaks while alone; such a speech",outside:true},
      {word:"entrechat",def:"a jump performed in ballet"},
      {word:"olecranon",def:"the outgrowth of tissue behind the elbow joint"},
      {word:"thaumatology",def:"the study or a discussion of miracles"},
      {word:"denuclearize",def:"to ban atomic weapons from; to reduce the number of atomic weapons"},
      {word:"paradigm",def:"a model",outside:true},
      {word:"myiasis",def:"the invasion and infestation of tissues by fly larvae; a disease which results from such infestation"},
      {word:"snickersnee",def:"a kind of knife"},
      {word:"Minotaur",def:"Greek Mythology. a monster"},
      {word:"Achilles' heel",def:"a weakness that seems small but is actually deadly"},
      {word:"Rottweiler",def:"a breed of large dog",outside:true}
    ]
  },
  "meet3": {
    name: "Virtual Challenge Meet #3",
    audio: {
      "words1-40": "audio/meet3-words-1-40.mp3",
      "words41-70": "audio/meet3-words-41-70.mp3",
      "tiebreaker": "audio/meet3-tiebreaker-1-20.mp3"
    },
    words: [
      {word:"pomology",def:"the study that deals with fruit and fruit cultivation"},
      {word:"Appomattox",def:"a town in Virginia known as the site where Robert E. Lee surrendered to end the Civil War",outside:true},
      {word:"sarcoptic mange",def:"a kind of skin disease caused by a mite"},
      {word:"platyrrhine",def:"relating to a group of primates that includes New World monkeys",outside:true},
      {word:"repentant",def:"sorrowful; characterized by guilt"},
      {word:"instantaneous",def:"done without delay; done as quickly as possible; happening at a specific moment"},
      {word:"Aeschylus",def:"a Greek dramatist"},
      {word:"Romano",def:"a kind of cheese"},
      {word:"Nietzsche",def:"a German philosopher"},
      {word:"sacerdotalism",def:"a theological belief that priests are mediators between man and God"},
      {word:"perionychium",def:"the border of tissue which surrounds a nail of the finger or toe",outside:true},
      {word:"duumvirate",def:"an executive board in the Roman Republic made up of two people; a two person partnership"},
      {word:"advection",def:"a change in things such as temperature in an air mass"},
      {word:"disbursal",def:"the act of paying or expending"},
      {word:"Qattara Depression",def:"an area in Egypt"},
      {word:"curmudgeon",def:"a person who is ill-tempered"},
      {word:"retinoscopy",def:"a kind of eye examination"},
      {word:"Doppler effect",def:"the change in sound or light waves depending upon where the source is relative to the person who hears or sees them",outside:true},
      {word:"de rigueur",def:"such that it is required by current custom"},
      {word:"iatrogenic",def:"caused by the activity or manner of a physician"},
      {word:"dendritic",def:"having to do with or like a kind of mineral that crystallizes in another mineral in a treelike form; like a tree"},
      {word:"arraignment",def:"a hearing in which the accused can hear and answer the charges made"},
      {word:"executrix",def:"Law. a female designated to enact the conditions or terms of a will"},
      {word:"vacuity",def:"emptiness; a space that is empty; idleness; the condition of being devoid of something"},
      {word:"antebellum",def:"belonging to the period prior to a war, especially the Civil War fought in America",outside:true},
      {word:"charge d'affaires",def:"a diplomat who fills in for a minister or ambassador who is away; a low-ranking diplomat"},
      {word:"Halcyon",def:"a genus of birds"},
      {word:"rhinencephalon",def:"a region of the brain"},
      {word:"solfatara",def:"an area of a volcano that gives off gases and steam"},
      {word:"funereal",def:"having to do with a service honoring a person who has died; sad"},
      {word:"maceration",def:"the act of soaking something in liquid; wasting away or drying up"},
      {word:"calumnious",def:"defamatory"},
      {word:"byssus",def:"Zoology. filaments used by some mollusks to attach themselves to surfaces; a kind of linen",outside:true},
      {word:"Mosaic",def:"having to do with the Hebrew prophet"},
      {word:"simian",def:"(adj.) having to do with a monkey or an ape | (n.) a monkey or an ape"},
      {word:"microampere",def:"a unit used to measure an electric current"},
      {word:"blastula",def:"Embryology. an embryonic form developed early"},
      {word:"piosity",def:"an often exaggerated display of being devout"},
      {word:"treacly",def:"too sweet; too sentimental",outside:true},
      {word:"fleche",def:"a spire such as one might see on a church"},
      {word:"tergiversate",def:"to be evasive in speaking; to waffle or change sides"},
      {word:"rhesus monkey",def:"a kind of animal"},
      {word:"masculinity",def:"the quality or condition of being male"},
      {word:"chassepot",def:"a kind of rifle"},
      {word:"andouille",def:"a kind of sausage which is spicy",outside:true},
      {word:"pharaoh hound",def:"a kind of hunting dog"},
      {word:"chameleonic",def:"able to adapt appearance or behavior to different situations or environments",outside:true},
      {word:"missa cantata",def:"a kind of Mass"},
      {word:"iridescence",def:"the quality or state of being lustrous"},
      {word:"reconnoiter",def:"to survey or inspect to gain information, especially information valuable militarily",outside:true},
      {word:"limacine",def:"having to do with or like a slug"},
      {word:"agnosia",def:"loss of the ability to interpret sounds or images"},
      {word:"Teotihuacan",def:"an ancient city in Mexico"},
      {word:"Petrarchan sonnet",def:"a kind of poem"},
      {word:"kineticism",def:"a kind of art or the theory of art involving movement"},
      {word:"medevac",def:"the movement of a person by aircraft to a hospital; an aircraft used for such purposes",outside:true},
      {word:"hypnophobia",def:"a very strong, abnormal fear of falling asleep"},
      {word:"subreption",def:"a deliberate misrepresentation by not revealing all important information"},
      {word:"Timor",def:"an island"},
      {word:"Hibernia",def:"a name used for Ireland"},
      {word:"amnesiac",def:"one who suffers from a loss of memory"},
      {word:"rite of passage",def:"a ceremony that commemorates the transition from one period of a person's life to another"},
      {word:"Icarus",def:"a mythological figure who flew too close to the sun",outside:true},
      {word:"chiliad",def:"a group made up of 1000; a millennium"},
      {word:"brocatelle",def:"a heavy fabric with raised designs"},
      {word:"salience",def:"the quality or condition of being prominent or of protruding"},
      {word:"myelogram",def:"a kind of x-ray used to examine the spinal cord",outside:true},
      {word:"zwieback",def:"a kind of bread"},
      {word:"depletion",def:"the act or process of using up, weakening, or exhausting"},
      {word:"trebuchet",def:"a kind of medieval catapult from which heavy stones were hurled",outside:true}
    ]
  },
  "meet4": {
    name: "Virtual Challenge Meet #4",
    audio: {
      "words1-40": "audio/meet4-words-1-40.mp3",
      "words41-70": "audio/meet4-words-41-70.mp3",
      "tiebreaker": "audio/meet4-tiebreaker-1-20.mp3"
    },
    words: [
      {word:"litigate",def:"Law. to cause to undergo a legal proceeding; to be involved in legal proceedings"},
      {word:"mycetoma",def:"nodules caused by bacteria, usually found on the leg or foot"},
      {word:"tacit",def:"silent; implied"},
      {word:"fanfaronade",def:"swaggering or boasting; flourish"},
      {word:"tenuous",def:"thin and long; dilute; flimsy"},
      {word:"caribou",def:"a type of large deer",outside:true},
      {word:"Melbourne",def:"a city in Australia"},
      {word:"histrionic",def:"having to do with acting; overly emotional"},
      {word:"shofar",def:"Judaism. a kind of trumpet"},
      {word:"Bataan",def:"a peninsula located in the Philippines"},
      {word:"tumorigenic",def:"capable of causing an abnormal growth of tissue"},
      {word:"nacre",def:"mother-of-pearl",outside:true},
      {word:"rescind",def:"to annul; to make void"},
      {word:"meteoroid",def:"a solid body which moves through space"},
      {word:"coup de grace",def:"a deathblow; an event that is decisive"},
      {word:"submergence",def:"the state of being put under water"},
      {word:"Qu'Appelle River",def:"a large natural stream in Canada"},
      {word:"irrecusable",def:"such that it is not subject to objection or challenge"},
      {word:"stem christie",def:"Sports. a kind of turn made in skiing"},
      {word:"topsy-turvy",def:"in a position so that the upper part is down and the bottom part is up; in a state of total disorder",outside:true},
      {word:"nonchalant",def:"unconcerned; calm and composed"},
      {word:"Peripatetic",def:"(adj.) related to the philosophy of Aristotle | (n.) a follower of this philosophy"},
      {word:"Komodo dragon",def:"a kind of lizard"},
      {word:"superciliary",def:"having to do with the area of the eyebrow; situated over the eye or eyebrow"},
      {word:"Jamaica",def:"an island in the West Indies",outside:true},
      {word:"inculcate",def:"to imbue by repetition; to teach"},
      {word:"luminosity",def:"the condition or quality of shining or glowing"},
      {word:"quaestor",def:"a financial and administrative public official in ancient Rome"},
      {word:"Rhodes scholar",def:"a student who receives a financial grant to attend Oxford University"},
      {word:"surcingle",def:"a girth used to bind something such as a saddle or blanket to a horse"},
      {word:"catechumen",def:"a person being instructed in the principles of Christianity",outside:true},
      {word:"uraeus",def:"the emblem of a serpent used by ancient Egyptian rulers"},
      {word:"revisionary",def:"the work or process of changing or amending something"},
      {word:"umlaut",def:"a diacritical mark",outside:true},
      {word:"unflappable",def:"not easily disturbed or excited; calm"},
      {word:"baleen whale",def:"a large marine mammal"},
      {word:"sensor",def:"a device which receives signals and responds to them"},
      {word:"Ramadan",def:"according to the Muslim calendar, the ninth month; a fast observed during this period"},
      {word:"carcinoma",def:"a kind of tumor",outside:true},
      {word:"revelation",def:"a disclosure; an insight that happens suddenly"},
      {word:"aberrated",def:"having defects or deviations from what one might expect"},
      {word:"vigoroso",def:"Music. with spirit (used as a direction)"},
      {word:"tritanopia",def:"a visual defect causing a person not to be able to discern blue and yellow"},
      {word:"nucleophile",def:"a kind of chemical compound"},
      {word:"impenitent",def:"not contrite or remorseful",outside:true},
      {word:"poinciana",def:"a kind of tree"},
      {word:"intumesce",def:"to enlarge; to bubble up"},
      {word:"keeshond",def:"a kind of dog",outside:true},
      {word:"ornithosis",def:"a disease carried by birds and contracted by humans"},
      {word:"recidivist",def:"one who goes back to a bad behavior, especially criminal behavior"},
      {word:"organically",def:"in a manner derived from living things without the use of synthetics"},
      {word:"oppugned",def:"(past tense) to call something into question",outside:true},
      {word:"misally",def:"to enter unwisely into an association or agreement"},
      {word:"Cassiopeia",def:"a constellation"},
      {word:"lanuginous",def:"covered with hairs like down"},
      {word:"Zapata mustache",def:"hair grown on the upper lip and allowed to curve downward on the sides"},
      {word:"nidicolous",def:"living in the nest until the skill needed to fly is developed (used of birds)"},
      {word:"abbatial",def:"having to do with a kind of monastery or convent"},
      {word:"ytterbium",def:"a metallic element with atomic number 70",outside:true},
      {word:"rhodolite",def:"a variety of garnet"},
      {word:"Cistercian",def:"a member of a monastic order founded in 1098 in France"},
      {word:"viticulture",def:"the growing of grapes"},
      {word:"maelstrom",def:"a chaotic or violent situation; a whirlpool",outside:true},
      {word:"entry-level",def:"appropriate for an inexperienced worker or person"},
      {word:"vinasse",def:"the remaining residue after distillation"},
      {word:"ambit",def:"a boundary; the sphere, scope, or range of something"},
      {word:"ventifact",def:"a stone shaped or polished by sand driven by wind"},
      {word:"expose",def:"the revelation of something that harms a person's reputation; a formal statement of facts"},
      {word:"caseous",def:"like cheese"},
      {word:"yucca",def:"a kind of plant",outside:true}
    ]
  }
};

// Function to analyze word morphology (prefixes/suffixes)
function analyzeWord(word) {
  const lower = word.toLowerCase().replace(/[^a-z-]/g, '');
  const result = { prefixes: [], suffixes: [], root: lower };

  // Check prefixes
  const sortedPrefixes = Object.keys(PREFIXES).sort((a, b) => b.length - a.length);
  for (const prefix of sortedPrefixes) {
    const clean = prefix.replace('-', '');
    if (lower.startsWith(clean) && lower.length > clean.length + 2) {
      result.prefixes.push({ prefix: prefix, meaning: PREFIXES[prefix] });
      result.root = lower.slice(clean.length);
      break;
    }
  }

  // Check suffixes
  const sortedSuffixes = Object.keys(SUFFIXES).sort((a, b) => b.length - a.length);
  for (const suffix of sortedSuffixes) {
    const clean = suffix.replace('-', '');
    if (lower.endsWith(clean) && lower.length > clean.length + 2) {
      result.suffixes.push({ suffix: suffix, meaning: SUFFIXES[suffix] });
      result.root = result.root.slice(0, result.root.length - clean.length);
      break;
    }
  }

  return result;
}

// Vocabulary fill-in-the-blank questions from UIL meets
var VOCAB_QUESTIONS = [
  // Meet #1
  {sentence:"The botanist noted that the leaf's surface was distinctly _____, giving it a soft, silvery sheen under the microscope.",options:["sericeous","bagasse","acaulescent","multilateral","cephalic"],answer:"sericeous"},
  {sentence:"In early medicine, physicians often relied on _____ to seal wounds and reduce the risk of infection before the advent of antiseptics.",options:["inoculation","patency","ingesta","cauterization","osteopathy"],answer:"cauterization"},
  {sentence:"The brilliant red color seen in fireworks displays is commonly produced by compounds of _____.",options:["gentian violet","vinasse","bergamot","rhodolite","strontium"],answer:"strontium"},
  {sentence:"During the 2020 pandemic, many experts in _____ were consulted to devise a plan to get the nation's workforce reactivated.",options:["pomology","macroeconomics","antipersonnel","exodontics","subornation"],answer:"macroeconomics"},
  {sentence:"After the Apollo missions returned lunar rock samples, the field of _____ expanded rapidly as scientists analyzed the Moon's geology.",options:["selenology","prosopography","thaumatology","somatology","biostatistics"],answer:"selenology"},
  {sentence:"At the Scandinavian food festival, visitors enjoyed slices of _____ paired with crisp bread and fruit preserves.",options:["en brochette","mulligatawny","Jarlsberg","tantara","brio"],answer:"Jarlsberg"},
  {sentence:"The veterinarian _____ the feral cat so that she could safely provide care for the frantic feline.",options:["vaticinated","queued","sedated","lyophilized","amalgamated"],answer:"sedated"},
  {sentence:"Gauntness and degeneration are synonymous with _____.",options:["escarpment","afforestation","obfuscation","acquittance","emaciation"],answer:"emaciation"},
  {sentence:"Known worldwide for his exquisite work with gems, the _____ was asked to prepare rubies and emeralds for a royal crown.",options:["equerry","lapidarian","quadrumvirate","poltroon","wainwright"],answer:"lapidarian"},
  {sentence:"Unlike precocial chicks that wander almost immediately, robins are _____ and remain in the nest for weeks.",options:["motile","rupicolous","viviparous","nidicolous","valgus"],answer:"nidicolous"},
  {sentence:"The surgeon explained that the knee joint is formed in part by the femur's medial _____.",options:["fremitus","sternocleidomastoid","condyle","amphorae","coccyx"],answer:"condyle"},
  {sentence:"The judge gave a harsher sentence because the defendant was a known _____ with multiple prior convictions.",options:["recidivist","librettist","sluggard","nabob","genealogist"],answer:"recidivist"},
  {sentence:"On summer mornings, a sky dotted with _____ clouds can signal unsettled weather later in the day.",options:["auriferous","harmattan","prelapsarian","sylvatic","altocumulus"],answer:"altocumulus"},
  {sentence:"In 17th-century European armies, a _____ was originally tasked with throwing small explosive bombs by hand.",options:["festschrift","dynamo","swashbuckler","grenadier","janissary"],answer:"grenadier"},
  {sentence:"The court ordered the burglar to pay full _____ to the store for the stolen merchandise.",options:["rapprochement","restitution","exemplum","salience","commination"],answer:"restitution"},
  // Meet #2
  {sentence:"The poor librarian was traumatized by the thunderous _____ caused by thousands of books crashing to the hardwood floor as several bookcases toppled like dominoes.",options:["taradiddle","farandole","altercation","reverie","bouleversement"],answer:"bouleversement"},
  {sentence:"The epidemiologist studied the _____ diseases transmitted by biological vectors such as flies and rodents.",options:["pestilential","potable","cephalic","ethereal","unwonted"],answer:"pestilential"},
  {sentence:"We received many _____ cards after our grandmother passed away.",options:["tenuous","refulgent","condolatory","prefatory","nuncupative"],answer:"condolatory"},
  {sentence:"The word _____ is derived from Breton roots meaning 'stone' and 'long.'",options:["nabob","mukluk","Bauhaus","keffiyeh","menhir"],answer:"menhir"},
  {sentence:"In traditional Indian dress, a colorful _____ often accompanies a sherwani or formal tunic.",options:["janissary","cummerbund","langlauf","mal de mer","quondam"],answer:"cummerbund"},
  {sentence:"Boastful and bragging are synonymous with _____.",options:["rumbustious","siccative","incommodious","thrasonical","efficacious"],answer:"thrasonical"},
  {sentence:"The _____ monks are known for their devotion to manual labor, silence, and simple living.",options:["dystopian","Cistercian","librettist","Tophet","Rotarian"],answer:"Cistercian"},
  {sentence:"The stop-and-go traffic on the scorching highway and no air conditioner in the car made the commute absolutely _____.",options:["torturous","pellucid","infinitesimal","cacophonous","flagitious"],answer:"torturous"},
  {sentence:"Because of its location on the equator in South America, _____ experiences roughly equal hours of daylight and night year-round.",options:["Zululand","Bataan","Ecuador","Damascus","Saarland"],answer:"Ecuador"},
  {sentence:"The violinist used a graceful _____ to connect the two notes seamlessly during the solo.",options:["dulcimer","tantara","subito","paisano","portamento"],answer:"portamento"},
  {sentence:"Emails and messages _____ in her inbox, each demanding her attention.",options:["spangled","queued","ceded","repined","emendated"],answer:"queued"},
  {sentence:"In team projects, being _____ helps ensure that everyone understands the goals and responsibilities.",options:["communicative","abbatial","peccant","fiducial","expeditionary"],answer:"communicative"},
  {sentence:"In the Alps, herders practice _____ by leading cattle uphill in summer and back to the valleys in winter.",options:["harmattan","echolocation","eminent domain","transhumance","acculturation"],answer:"transhumance"},
  {sentence:"The Romans advanced _____ throughout Europe, laying the foundation for many of today's famous wine regions.",options:["lexicography","obfuscation","brusquerie","viticulture","escarpment"],answer:"viticulture"},
  {sentence:"The _____ is unique among marsupials because both males and females have watertight pouches for swimming.",options:["faun","red herring","yapok","serval","zebu"],answer:"yapok"},
  // Meet #3
  {sentence:"The _____ shape of the moon almost looked like the blade of a sickle.",options:["mandala","falcate","multilateral","arborescent","tenuous"],answer:"falcate"},
  {sentence:"The noun _____ is derived from the Old French root meaning 'peasant.'",options:["panacean","paisano","praenomen","pleuston","portiere"],answer:"paisano"},
  {sentence:"The _____ bones in her foot were caused from years of wearing ill-fitting shoes.",options:["cephalic","organoleptic","valgus","sylvatic","diatomaceous"],answer:"valgus"},
  {sentence:"The tour guide explained that the _____ residence belonged to the head of the monastery.",options:["manorial","coadunate","dystopian","abbatial","histrionic"],answer:"abbatial"},
  {sentence:"The _____ was far too steep to climb without special equipment.",options:["aquifer","escarpment","condyle","equerry","polynya"],answer:"escarpment"},
  {sentence:"The sizable antlers of the male _____ may tower four feet above his head.",options:["mandrill","whelk","wapiti","guillemot","serval"],answer:"wapiti"},
  {sentence:"As the old lady was mugged, the _____ gawked or walked away and did nothing to help protect her from her attackers.",options:["gadflies","prima donnas","grenadiers","nabobs","poltroons"],answer:"poltroons"},
  {sentence:"The powerful aroma of burgers on the grill was _____ in attracting customers to the food truck.",options:["efficacious","quondam","tenebrific","enigmatical","auriferous"],answer:"efficacious"},
  {sentence:"Synonymous with _____ are slogan and shibboleth.",options:["underpinning","langlauf","brio","watchword","exemplum"],answer:"watchword"},
  {sentence:"The artist's paintings were considered _____ because they depicted skeletons, shadows, and scenes of death in unsettling detail.",options:["macabre","antipersonnel","incommodious","circumspect","apocalyptic"],answer:"macabre"},
  {sentence:"In public health studies, _____ is often discussed as a foodborne disease that can mimic appendicitis in children.",options:["mal de mer","ranula","yersiniosis","scotoma","deuteranopia"],answer:"yersiniosis"},
  {sentence:"As we entered the gym, we were overwhelmed with the _____ sounds of the exercise machines and heavy weights reverberating as they collided.",options:["apatetic","flagitious","ethereal","peccant","cacophonous"],answer:"cacophonous"},
  {sentence:"Ancient oracles were believed to _____ future events through prophecy and divine insight.",options:["repine","vaticinate","amalgamate","deploy","lyophilize"],answer:"vaticinate"},
  {sentence:"_____ is a country located on the southern edge of the Arabian Peninsula, bordered by Saudi Arabia and Oman.",options:["Namibia","Bataan","Damascus","Yemen","Zululand"],answer:"Yemen"},
  {sentence:"The _____ in western Africa created a haze that limited visibility and partially blocked sunlight.",options:["harmattan","yurt","bergamot","silage","tantara"],answer:"harmattan"},
  // Meet #4
  {sentence:"Medication helped reduce his _____ during the rough ocean crossing.",options:["mal de mer","anamnesis","yersiniosis","scotoma","valgus"],answer:"mal de mer"},
  {sentence:"The villagers whispered that a _____ haunted the old road, appearing on foggy nights as a sign of death.",options:["tantara","wraith","brusquerie","pleuston","reverie"],answer:"wraith"},
  {sentence:"Incorporating obviously staged and scripted drama, many 'reality' shows rely on the _____ to believe that these ridiculous performances are actual events.",options:["rime riche","opera bouffe","Fascisti","pisciculture","booboisie"],answer:"booboisie"},
  {sentence:"After dropping her phone in the swimming pool, Linda placed the device in a container filled with rice hoping it would _____ it.",options:["cathect","emendate","tergiversate","desiccate","amalgamate"],answer:"desiccate"},
  {sentence:"Ian pursued a degree in botany focusing on the _____ of citrus fruits.",options:["exodontics","methodology","somatology","pomology","stichometry"],answer:"pomology"},
  {sentence:"The word _____ originates from a Latin root meaning 'to grow together.'",options:["concrescence","leachate","arborescent","festschrift","escarpment"],answer:"concrescence"},
  {sentence:"_____ gained independence from South Africa in 1990.",options:["Saarland","Yemen","Namibia","Quirinal","Damascus"],answer:"Namibia"},
  {sentence:"A _____ uses its height and sharp hearing to hunt rodents in tall grass.",options:["rhesus monkey","serval","guillemot","zebu","whelk"],answer:"serval"},
  {sentence:"Ancient Greeks used _____ to store and transport wine, oil, and grain.",options:["crampons","gimmals","silage","portiere","amphorae"],answer:"amphorae"},
  {sentence:"The theory of thesis, antithesis, and synthesis is commonly associated with _____.",options:["phantasmagoria","rapprochement","Hegelianism","Midrash","obfuscation"],answer:"Hegelianism"},
  {sentence:"The campsite offered guests the chance to stay overnight in a modern _____.",options:["Bauhaus","yurt","mandala","palindrome","keffiyeh"],answer:"yurt"},
  {sentence:"The judges discussed the matter _____ before announcing their decision publicly.",options:["nefariously","metabolically","subito","inter se","counterfactual"],answer:"inter se"},
  {sentence:"Synonymous with _____ would be diaphanous and celestial.",options:["ethereal","unwonted","apocalyptic","prelapsarian","nuncupative"],answer:"ethereal"},
  {sentence:"Mosquitoes thrive in _____ areas where wetlands and swamps are common.",options:["rupicolous","cismontane","paludal","auriferous","fissipalmate"],answer:"paludal"},
  {sentence:"Dandelions are an example of _____ plants, with flowers rising directly from the base rather than a stem.",options:["falcate","acaulescent","scansorial","multilateral","diatomaceous"],answer:"acaulescent"}
];
