// UIL Spelling & Vocabulary Practice - Reference Data
// Prefixes, suffixes, practice tests, and word analysis

// Common prefixes with meanings for analysis
const PREFIXES = {
  "a-": "not, without",
  "ab-": "away from",
  "ad-": "toward, to",
  "aero-": "air",
  "agro-": "field, agriculture",
  "alpha-": "first",
  "an-": "not, without",
  "ana-": "up, back, again",
  "ante-": "before",
  "anti-": "against, opposite",
  "auto-": "self",
  "bi-": "two",
  "bio-": "life",
  "cata-": "down",
  "centi-": "hundred",
  "circum-": "around",
  "co-": "together, with",
  "com-": "together, with",
  "con-": "together, with",
  "contra-": "against",
  "counter-": "against",
  "de-": "down, from, reverse",
  "deca-": "ten",
  "demi-": "half",
  "di-": "two",
  "dia-": "through, across",
  "dis-": "not, apart",
  "dys-": "bad, difficult",
  "eco-": "environment",
  "em-": "in, into",
  "en-": "in, into, cause",
  "endo-": "within",
  "epi-": "upon, above",
  "equi-": "equal",
  "eu-": "good, well",
  "ex-": "out of, former",
  "exo-": "outside",
  "extra-": "beyond",
  "fore-": "before, front",
  "geo-": "earth",
  "hemi-": "half",
  "hetero-": "different",
  "homo-": "same",
  "hydro-": "water",
  "hyper-": "over, excessive",
  "hypo-": "under, below",
  "il-": "not",
  "im-": "not, into",
  "in-": "not, into",
  "infra-": "below",
  "inter-": "between, among",
  "intra-": "within",
  "ir-": "not",
  "iso-": "equal",
  "macro-": "large",
  "mal-": "bad",
  "mega-": "large, great",
  "meta-": "beyond, change",
  "micro-": "small",
  "mid-": "middle",
  "milli-": "thousand",
  "mini-": "small",
  "mis-": "wrong, bad",
  "mono-": "one, single",
  "multi-": "many",
  "neo-": "new",
  "neuro-": "nerve",
  "non-": "not",
  "ob-": "against",
  "omni-": "all",
  "over-": "excessive",
  "paleo-": "ancient",
  "pan-": "all",
  "para-": "beside, beyond",
  "peri-": "around",
  "photo-": "light",
  "poly-": "many",
  "post-": "after",
  "pre-": "before",
  "pro-": "forward, in favor",
  "proto-": "first",
  "pseudo-": "false",
  "psycho-": "mind",
  "quadr-": "four",
  "quasi-": "seemingly",
  "re-": "again, back",
  "retro-": "backward",
  "sacro-": "sacred",
  "self-": "self",
  "semi-": "half, partly",
  "sub-": "under, below",
  "super-": "above, beyond",
  "supra-": "above",
  "sym-": "together",
  "syn-": "together",
  "tele-": "far, distant",
  "trans-": "across, beyond",
  "tri-": "three",
  "ultra-": "beyond, extreme",
  "un-": "not, reverse",
  "under-": "below, less",
  "uni-": "one",
  "vice-": "in place of"
};

// Common suffixes with meanings
const SUFFIXES = {
  "-able": "capable of being",
  "-ible": "capable of being",
  "-aceous": "resembling, relating to",
  "-acious": "having quality of",
  "-acity": "quality of",
  "-ade": "action, product",
  "-age": "action, state",
  "-al": "relating to",
  "-an": "relating to, native of",
  "-ance": "state, quality",
  "-ancy": "state, quality",
  "-ant": "one who, performing",
  "-ar": "relating to",
  "-arian": "one who, believer in",
  "-ary": "relating to, place for",
  "-ate": "having, cause to be",
  "-ation": "action, process",
  "-ative": "tending to",
  "-cide": "killing",
  "-cracy": "rule, government",
  "-crat": "ruler",
  "-dom": "state, realm",
  "-ean": "relating to",
  "-ectomy": "surgical removal",
  "-ee": "one who receives",
  "-emia": "blood condition",
  "-ence": "state, quality",
  "-ency": "state, quality",
  "-ent": "performing, causing",
  "-eous": "having nature of",
  "-er": "one who, more",
  "-ery": "place, practice",
  "-escence": "becoming",
  "-escent": "becoming",
  "-esque": "in the style of",
  "-ess": "female",
  "-est": "most",
  "-etic": "relating to",
  "-ette": "small, feminine",
  "-eur": "one who",
  "-ful": "full of",
  "-fy": "make, cause",
  "-gamy": "marriage",
  "-genic": "producing",
  "-geny": "origin, production",
  "-gon": "angle",
  "-gram": "written, drawn",
  "-graph": "writing, instrument",
  "-graphy": "writing, description",
  "-ia": "condition, region",
  "-ial": "relating to",
  "-ian": "relating to, one who",
  "-iasis": "disease condition",
  "-iatric": "medical treatment",
  "-ible": "capable of",
  "-ic": "relating to",
  "-ical": "relating to",
  "-ician": "specialist",
  "-ics": "science, study",
  "-id": "having quality of",
  "-ify": "make, cause to be",
  "-ile": "capable of, relating to",
  "-ine": "relating to, resembling",
  "-ion": "action, condition",
  "-ious": "having quality of",
  "-ism": "doctrine, practice",
  "-ist": "one who practices",
  "-istic": "relating to",
  "-ite": "native, follower",
  "-itis": "inflammation",
  "-itude": "state, quality",
  "-ity": "state, quality",
  "-ive": "tending to, having nature of",
  "-ization": "process of making",
  "-ize": "make, cause to be",
  "-kinesis": "movement",
  "-less": "without",
  "-like": "resembling",
  "-ling": "small, young",
  "-logy": "study of",
  "-ly": "in manner of",
  "-mania": "obsession",
  "-ment": "action, result",
  "-meter": "measuring device",
  "-metry": "measurement",
  "-morph": "form, shape",
  "-ness": "state, quality",
  "-nomy": "system of laws",
  "-oid": "resembling",
  "-ology": "study of",
  "-oma": "tumor, mass",
  "-opia": "vision condition",
  "-or": "one who",
  "-ory": "place for, relating to",
  "-osis": "condition, process",
  "-ous": "full of, having",
  "-pathy": "feeling, disease",
  "-phage": "eating",
  "-phagy": "eating",
  "-phile": "loving",
  "-philia": "love of",
  "-phobia": "fear of",
  "-phone": "sound",
  "-phyte": "plant",
  "-plasm": "formed substance",
  "-plasty": "surgical repair",
  "-pod": "foot",
  "-scope": "viewing instrument",
  "-scopy": "viewing",
  "-ship": "state, office",
  "-sis": "condition, process",
  "-some": "characterized by",
  "-stasis": "standing, stopping",
  "-tion": "action, state",
  "-tomy": "cutting",
  "-tude": "state, quality",
  "-ular": "relating to",
  "-ulent": "full of",
  "-ure": "action, process",
  "-ward": "direction",
  "-wise": "manner",
  "-y": "characterized by"
};

// Common word roots with meanings, origins, and examples
const COMMON_ROOTS = [
  {root:"act",meaning:"do, drive",origin:"Latin",examples:["action","activate","react"]},
  {root:"anim",meaning:"life, spirit",origin:"Latin",examples:["animal","animate","unanimous"]},
  {root:"aqua",meaning:"water",origin:"Latin",examples:["aquifer","aqueous","aquarium"]},
  {root:"aud",meaning:"hear",origin:"Latin",examples:["audience","auditory","audible"]},
  {root:"bene",meaning:"good, well",origin:"Latin",examples:["benefit","benevolent","benediction"]},
  {root:"biblio",meaning:"book",origin:"Greek",examples:["bibliography","bibliophile","bible"]},
  {root:"cap",meaning:"head, take",origin:"Latin",examples:["capital","capture","capable"]},
  {root:"carn",meaning:"flesh",origin:"Latin",examples:["carcinoma","carnivore","incarnate"]},
  {root:"chron",meaning:"time",origin:"Greek",examples:["chronic","chronicle","chronology"]},
  {root:"cide",meaning:"kill",origin:"Latin",examples:["homicide","pesticide","fratricide"]},
  {root:"cogn",meaning:"know",origin:"Latin",examples:["cognoscente","recognize","cognition"]},
  {root:"corp",meaning:"body",origin:"Latin",examples:["corpse","corporation","incorporate"]},
  {root:"cred",meaning:"believe",origin:"Latin",examples:["credit","incredible","credentials"]},
  {root:"derm",meaning:"skin",origin:"Greek",examples:["dermatology","epidermis","hypodermic"]},
  {root:"dict",meaning:"say, speak",origin:"Latin",examples:["dictum","predict","dictionary"]},
  {root:"duc",meaning:"lead",origin:"Latin",examples:["conduct","educate","produce"]},
  {root:"fac",meaning:"make, do",origin:"Latin",examples:["factory","manufacture","facilitate"]},
  {root:"gen",meaning:"birth, origin",origin:"Greek",examples:["genome","genesis","generate"]},
  {root:"graph",meaning:"write",origin:"Greek",examples:["biography","photograph","autograph"]},
  {root:"ject",meaning:"throw",origin:"Latin",examples:["project","eject","injection"]},
  {root:"lith",meaning:"stone",origin:"Greek",examples:["lithograph","monolith","megalith"]},
  {root:"log",meaning:"word, study",origin:"Greek",examples:["biology","dialogue","etymology"]},
  {root:"luc",meaning:"light",origin:"Latin",examples:["lucid","translucent","elucidate"]},
  {root:"manu",meaning:"hand",origin:"Latin",examples:["manual","manuscript","manufacture"]},
  {root:"morph",meaning:"form, shape",origin:"Greek",examples:["metamorphosis","amorphous","morphology"]},
  {root:"nat",meaning:"born",origin:"Latin",examples:["native","natural","prenatal"]},
  {root:"path",meaning:"feeling, disease",origin:"Greek",examples:["sympathy","pathology","empathy"]},
  {root:"ped",meaning:"foot",origin:"Latin",examples:["pedestrian","pedal","impede"]},
  {root:"phil",meaning:"love",origin:"Greek",examples:["xenophile","philosophy","philanthropy"]},
  {root:"phon",meaning:"sound",origin:"Greek",examples:["telephone","phonics","euphony"]},
  {root:"port",meaning:"carry",origin:"Latin",examples:["transport","import","portable"]},
  {root:"psych",meaning:"mind, soul",origin:"Greek",examples:["psychology","psychosis","psyche"]},
  {root:"rupt",meaning:"break",origin:"Latin",examples:["rupture","interrupt","erupt"]},
  {root:"scrib",meaning:"write",origin:"Latin",examples:["prescribe","manuscript","scribble"]},
  {root:"sect",meaning:"cut",origin:"Latin",examples:["section","dissect","bisect"]},
  {root:"sens",meaning:"feel",origin:"Latin",examples:["sensor","sensible","sensitive"]},
  {root:"spec",meaning:"see, look",origin:"Latin",examples:["inspect","spectacle","specimen"]},
  {root:"struct",meaning:"build",origin:"Latin",examples:["structure","construct","instruct"]},
  {root:"terr",meaning:"earth, land",origin:"Latin",examples:["terrain","territory","terrestrial"]},
  {root:"therm",meaning:"heat",origin:"Greek",examples:["thermometer","thermal","geothermal"]},
  {root:"vac",meaning:"empty",origin:"Latin",examples:["vacuum","vacuity","evacuate"]},
  {root:"ven",meaning:"come",origin:"Latin",examples:["adventure","convention","prevent"]},
  {root:"vid",meaning:"see",origin:"Latin",examples:["video","evidence","provide"]},
  {root:"vit",meaning:"life",origin:"Latin",examples:["viticulture","vital","vitamin"]},
  {root:"voc",meaning:"voice, call",origin:"Latin",examples:["vocal","advocate","vocabulary"]}
];

// Practice test data from pronouncer keys
const PRACTICE_TESTS = {
  "meet1": {
    name: "Virtual Challenge Meet #1",
    audio: {
      "words1-40": "audio/meet1-words-1-40.mp3",
      "words41-70": "audio/meet1-words-41-70.mp3",
      "tiebreaker": "audio/meet1-tiebreaker-1-20.mp3"
    },
    words: [
      {word:"pediatrician",def:"a doctor who treats infants and children"},
      {word:"xenophile",def:"a person to whom foreign people and cultures are appealing"},
      {word:"genome",def:"an organism's hereditary material found in chromosomes, DNA, or RNA"},
      {word:"Eucalyptus",def:"a genus of trees"},
      {word:"cronyism",def:"showing friends or relatives special favor by appointing them to positions for which they are not qualified"},
      {word:"quintessential",def:"typical",outside:true},
      {word:"adroit",def:"dexterous; skillful"},
      {word:"consentaneous",def:"being in agreement"},
      {word:"toque",def:"a kind of hat or cap",outside:true},
      {word:"faun",def:"Roman Mythology. a mythological deity which is part man and part animal"},
      {word:"gurney",def:"a stretcher used to transport patients"},
      {word:"oxycephaly",def:"an abnormality in which the top of the head is pointed"},
      {word:"non prosequitur",def:"Law. a term indicating the judgment which is entered against someone who fails to appear in court to pursue a suit"},
      {word:"akaryocyte",def:"a cell which has no nucleus"},
      {word:"saute",def:"(v.) to fry briefly | (n.) food prepared in such a way"},
      {word:"chi-square",def:"a term used in statistics"},
      {word:"pyriform",def:"in the shape of a pear"},
      {word:"nolo contendere",def:"Law. a plea made by an accused which acknowledges guilt",outside:true},
      {word:"encroachment",def:"the act of advancing past limitations of rights or property; a type of football violation"},
      {word:"bangkok",def:"a kind of hat"},
      {word:"politesse",def:"the act of being courteous"},
      {word:"chancellor",def:"a high ranking official"},
      {word:"vesicate",def:"to blister"},
      {word:"arrhythmia",def:"a disturbance in the pattern and regularity of the heartbeat",outside:true},
      {word:"dictum",def:"a pronouncement; Law. a judge's opinion that is not binding"},
      {word:"Bauhaus",def:"having to do with a school of design"},
      {word:"penuche",def:"a confection made with brown sugar, milk, and nuts",alt:"penuchi"},
      {word:"multivoltine",def:"producing offspring several times in the same season"},
      {word:"theocentric",def:"placing God as the focal point"},
      {word:"irascible",def:"short-tempered",outside:true},
      {word:"scansorial",def:"Zoology. adapted for climbing"},
      {word:"ostensibly",def:"in a manner that is outward or apparent"},
      {word:"nevus",def:"a birthmark or mole",outside:true},
      {word:"algorism",def:"the Arabic system of numerals; computation using such numerals"},
      {word:"vaporescence",def:"the formation of something such as fog, mist, steam, etc."},
      {word:"spinescent",def:"having bristles; ending in a bristle"},
      {word:"granulocyte",def:"a kind of white blood cell"},
      {word:"dhurrie",def:"a kind of rug made in India",outside:true},
      {word:"esophagus",def:"the part of the body through which food passes to the stomach",alt:"oesophagus"},
      {word:"lotus position",def:"a way of sitting used in yoga"},
      {word:"equilibrate",def:"to bring into balance"},
      {word:"youngberry",def:"a type of shrub; the fruit produced by this shrub"},
      {word:"henbane",def:"a kind of poisonous plant",outside:true},
      {word:"geophagy",def:"the eating of something such as clay or chalk"},
      {word:"attache case",def:"a slim container with hinges and a lock which is usually used to carry papers, books, etc.",outside:true},
      {word:"laetrile",def:"a substance sourced from amygdalin"},
      {word:"transitionary",def:"having to do with change or movement from one point to another"},
      {word:"gravitas",def:"seriousness of manner or conduct"},
      {word:"agouti",def:"a type of burrowing rodent; a type of grizzled fur"},
      {word:"gimmal",def:"a kind of ring; a device used in a clock"}
    ]
  },
  "meet2": {
    name: "Virtual Challenge Meet #2",
    audio: {
      "words1-40": "audio/meet2-words-1-40.mp3",
      "words41-70": "audio/meet2-words-41-70.mp3",
      "tiebreaker": "audio/meet2-tiebreaker-1-20.mp3"
    },
    words: [
      {word:"escarole",def:"a kind of endive"},
      {word:"Diogenes",def:"a Greek philosopher"},
      {word:"etymon",def:"an earlier version of a word that is the source for the derivative"},
      {word:"labret",def:"an ornament for a lip piercing"},
      {word:"Islamabad",def:"a city in Pakistan"},
      {word:"rubefacient",def:"(adj.) causing the skin to turn red | (n.) a substance that causes the skin to turn red"},
      {word:"arriere-pensee",def:"a reservation usually about the legitimacy of something"},
      {word:"spaceborne",def:"operating in the region beyond the atmosphere of Earth",outside:true},
      {word:"soubrette",def:"a character in a comedy or an opera; the person who plays such a part; a flirtatious woman"},
      {word:"Cinco de Mayo",def:"a day celebrated in some places as a commemoration of the defeat of French troops in 1862"},
      {word:"lyrebird",def:"a kind of feathered vertebrate"},
      {word:"antithesis",def:"a contrast; the exact opposite; a figure of speech"},
      {word:"Judea",def:"a region in the Middle East",alt:"Judaea"},
      {word:"demagoguery",def:"rabble rousing, agitation, or provocation"},
      {word:"ghoulish",def:"like a fiend or devil",outside:true},
      {word:"acoustooptics",def:"a science involving sound and sight"},
      {word:"bergamot",def:"a citrus plant; the oil from this plant"},
      {word:"chambered nautilus",def:"a type of mollusk"},
      {word:"Gouda",def:"a kind of cheese"},
      {word:"affenpinscher",def:"a breed of dogs",outside:true},
      {word:"cabaret",def:"a kind of nightclub that has performances; the show presented in such a nightclub"},
      {word:"Hippocrene",def:"Greek Mythology. a fountain which was believed to be a source of poetic inspiration"},
      {word:"tarboosh",def:"a kind of cap",alt:"tarbush"},
      {word:"leachate",def:"the solution or product resulting from water percolating through soil"},
      {word:"daedal",def:"intricate; artistic"},
      {word:"gyre",def:"(n.) a form that is spiral or circular; a motion that is spiral or circular | (v.) to spiral or whirl",outside:true},
      {word:"oleic acid",def:"an oily liquid used in making soap"},
      {word:"sericeous",def:"silky; Botany. covered with hairs that are like silk"},
      {word:"Beirut",def:"a city in Lebanon",outside:true},
      {word:"kegler",def:"Sports. a person who engages in bowling"},
      {word:"saxophone",def:"Music. a kind of instrument"},
      {word:"Gaelic",def:"having to do with people from Scotland, Ireland, or the Isle of Man who speak a certain language",outside:true},
      {word:"tempera",def:"a substance used in painting; a painting done with such a substance"},
      {word:"Havasupai",def:"a Native American people; a member of this group of people; the language spoken by this group of people"},
      {word:"maitre d'hotel",def:"the person in charge of the dining room staff in a restaurant; a steward or butler; a sauce"},
      {word:"cantonment",def:"the quartering of troops or the quarters for such troops; a military base in India"},
      {word:"punctilio",def:"a nicety or fine point related to etiquette; close adherence to formality"},
      {word:"radicchio",def:"a kind of plant"},
      {word:"U-boat",def:"a German naval submarine",outside:true},
      {word:"Gettysburg",def:"a town in Pennsylvania and the site of a Civil War battle"},
      {word:"coequal",def:"(adj.) being the same as another in size or rank | (n.) one who has the same value or quality as another"},
      {word:"heptathlon",def:"Sports. a contest that has seven events"},
      {word:"shalom",def:"(interjection) an expression used as a greeting or farewell by Jewish people"},
      {word:"rhonchus",def:"a sound similar to snoring caused by bronchial secretions"},
      {word:"metopic",def:"having to do with the forehead",outside:true},
      {word:"adversarial",def:"characteristic of an opponent"},
      {word:"paleozoology",def:"the branch of science that studies animal fossils and ancient animal life"},
      {word:"cliquish",def:"exclusive; partisan",outside:true},
      {word:"daiquiri",def:"a kind of drink"},
      {word:"chemurgy",def:"the development of new products often from agricultural materials"},
      {word:"otolaryngology",def:"a branch of medicine dealing with diseases affecting the ear, nose, and throat",outside:true},
      {word:"rapprochement",def:"the act of reestablishing good relations; reconciliation"},
      {word:"quadrennium",def:"a period of four years"},
      {word:"Naugahyde",def:"a trademark used for a kind of artificial leather"},
      {word:"heroic verse",def:"a form used in poetry"},
      {word:"melliferous",def:"such that it forms or bears honey"},
      {word:"lycanthropy",def:"in folklore, the ability to take on the characteristics and form of a wolf"},
      {word:"nine days' wonder",def:"something which happens and creates a sensation that lasts only for a short time"},
      {word:"postiche",def:"a sham; a toupee"},
      {word:"soliloquy",def:"a literary form in which one person speaks while alone; such a speech",outside:true},
      {word:"entrechat",def:"a jump performed in ballet"},
      {word:"olecranon",def:"the outgrowth of tissue behind the elbow joint"},
      {word:"thaumatology",def:"the study or a discussion of miracles"},
      {word:"denuclearize",def:"to ban atomic weapons from; to reduce the number of atomic weapons"},
      {word:"paradigm",def:"a model",outside:true},
      {word:"myiasis",def:"the invasion and infestation of tissues by fly larvae; a disease which results from such infestation"},
      {word:"snickersnee",def:"a kind of knife"},
      {word:"Minotaur",def:"Greek Mythology. a monster"},
      {word:"Achilles' heel",def:"a weakness that seems small but is actually deadly"},
      {word:"Rottweiler",def:"a breed of large dog",outside:true}
    ]
  },
  "meet3": {
    name: "Virtual Challenge Meet #3",
    audio: {
      "words1-40": "audio/meet3-words-1-40.mp3",
      "words41-70": "audio/meet3-words-41-70.mp3",
      "tiebreaker": "audio/meet3-tiebreaker-1-20.mp3"
    },
    words: [
      {word:"pomology",def:"the study that deals with fruit and fruit cultivation"},
      {word:"Appomattox",def:"a town in Virginia known as the site where Robert E. Lee surrendered to end the Civil War",outside:true},
      {word:"sarcoptic mange",def:"a kind of skin disease caused by a mite"},
      {word:"platyrrhine",def:"relating to a group of primates that includes New World monkeys",outside:true},
      {word:"repentant",def:"sorrowful; characterized by guilt"},
      {word:"instantaneous",def:"done without delay; done as quickly as possible; happening at a specific moment"},
      {word:"Aeschylus",def:"a Greek dramatist"},
      {word:"Romano",def:"a kind of cheese"},
      {word:"Nietzsche",def:"a German philosopher"},
      {word:"sacerdotalism",def:"a theological belief that priests are mediators between man and God"},
      {word:"perionychium",def:"the border of tissue which surrounds a nail of the finger or toe",outside:true},
      {word:"duumvirate",def:"an executive board in the Roman Republic made up of two people; a two person partnership"},
      {word:"advection",def:"a change in things such as temperature in an air mass"},
      {word:"disbursal",def:"the act of paying or expending"},
      {word:"Qattara Depression",def:"an area in Egypt"},
      {word:"curmudgeon",def:"a person who is ill-tempered"},
      {word:"retinoscopy",def:"a kind of eye examination"},
      {word:"Doppler effect",def:"the change in sound or light waves depending upon where the source is relative to the person who hears or sees them",outside:true},
      {word:"de rigueur",def:"such that it is required by current custom"},
      {word:"iatrogenic",def:"caused by the activity or manner of a physician"},
      {word:"dendritic",def:"having to do with or like a kind of mineral that crystallizes in another mineral in a treelike form; like a tree"},
      {word:"arraignment",def:"a hearing in which the accused can hear and answer the charges made"},
      {word:"executrix",def:"Law. a female designated to enact the conditions or terms of a will"},
      {word:"vacuity",def:"emptiness; a space that is empty; idleness; the condition of being devoid of something"},
      {word:"antebellum",def:"belonging to the period prior to a war, especially the Civil War fought in America",outside:true},
      {word:"charge d'affaires",def:"a diplomat who fills in for a minister or ambassador who is away; a low-ranking diplomat"},
      {word:"Halcyon",def:"a genus of birds"},
      {word:"rhinencephalon",def:"a region of the brain"},
      {word:"solfatara",def:"an area of a volcano that gives off gases and steam"},
      {word:"funereal",def:"having to do with a service honoring a person who has died; sad"},
      {word:"maceration",def:"the act of soaking something in liquid; wasting away or drying up"},
      {word:"calumnious",def:"defamatory"},
      {word:"byssus",def:"Zoology. filaments used by some mollusks to attach themselves to surfaces; a kind of linen",outside:true},
      {word:"Mosaic",def:"having to do with the Hebrew prophet"},
      {word:"simian",def:"(adj.) having to do with a monkey or an ape | (n.) a monkey or an ape"},
      {word:"microampere",def:"a unit used to measure an electric current"},
      {word:"blastula",def:"Embryology. an embryonic form developed early"},
      {word:"piosity",def:"an often exaggerated display of being devout"},
      {word:"treacly",def:"too sweet; too sentimental",outside:true},
      {word:"fleche",def:"a spire such as one might see on a church"},
      {word:"tergiversate",def:"to be evasive in speaking; to waffle or change sides"},
      {word:"rhesus monkey",def:"a kind of animal"},
      {word:"masculinity",def:"the quality or condition of being male"},
      {word:"chassepot",def:"a kind of rifle"},
      {word:"andouille",def:"a kind of sausage which is spicy",outside:true},
      {word:"pharaoh hound",def:"a kind of hunting dog"},
      {word:"chameleonic",def:"able to adapt appearance or behavior to different situations or environments",outside:true},
      {word:"missa cantata",def:"a kind of Mass"},
      {word:"iridescence",def:"the quality or state of being lustrous"},
      {word:"reconnoiter",def:"to survey or inspect to gain information, especially information valuable militarily",outside:true},
      {word:"limacine",def:"having to do with or like a slug"},
      {word:"agnosia",def:"loss of the ability to interpret sounds or images"},
      {word:"Teotihuacan",def:"an ancient city in Mexico"},
      {word:"Petrarchan sonnet",def:"a kind of poem"},
      {word:"kineticism",def:"a kind of art or the theory of art involving movement"},
      {word:"medevac",def:"the movement of a person by aircraft to a hospital; an aircraft used for such purposes",outside:true},
      {word:"hypnophobia",def:"a very strong, abnormal fear of falling asleep"},
      {word:"subreption",def:"a deliberate misrepresentation by not revealing all important information"},
      {word:"Timor",def:"an island"},
      {word:"Hibernia",def:"a name used for Ireland"},
      {word:"amnesiac",def:"one who suffers from a loss of memory"},
      {word:"rite of passage",def:"a ceremony that commemorates the transition from one period of a person's life to another"},
      {word:"Icarus",def:"a mythological figure who flew too close to the sun",outside:true},
      {word:"chiliad",def:"a group made up of 1000; a millennium"},
      {word:"brocatelle",def:"a heavy fabric with raised designs"},
      {word:"salience",def:"the quality or condition of being prominent or of protruding"},
      {word:"myelogram",def:"a kind of x-ray used to examine the spinal cord",outside:true},
      {word:"zwieback",def:"a kind of bread"},
      {word:"depletion",def:"the act or process of using up, weakening, or exhausting"},
      {word:"trebuchet",def:"a kind of medieval catapult from which heavy stones were hurled",outside:true}
    ]
  },
  "meet4": {
    name: "Virtual Challenge Meet #4",
    audio: {
      "words1-40": "audio/meet4-words-1-40.mp3",
      "words41-70": "audio/meet4-words-41-70.mp3",
      "tiebreaker": "audio/meet4-tiebreaker-1-20.mp3"
    },
    words: [
      {word:"litigate",def:"Law. to cause to undergo a legal proceeding; to be involved in legal proceedings"},
      {word:"mycetoma",def:"nodules caused by bacteria, usually found on the leg or foot"},
      {word:"tacit",def:"silent; implied"},
      {word:"fanfaronade",def:"swaggering or boasting; flourish"},
      {word:"tenuous",def:"thin and long; dilute; flimsy"},
      {word:"caribou",def:"a type of large deer",outside:true},
      {word:"Melbourne",def:"a city in Australia"},
      {word:"histrionic",def:"having to do with acting; overly emotional"},
      {word:"shofar",def:"Judaism. a kind of trumpet"},
      {word:"Bataan",def:"a peninsula located in the Philippines"},
      {word:"tumorigenic",def:"capable of causing an abnormal growth of tissue"},
      {word:"nacre",def:"mother-of-pearl",outside:true},
      {word:"rescind",def:"to annul; to make void"},
      {word:"meteoroid",def:"a solid body which moves through space"},
      {word:"coup de grace",def:"a deathblow; an event that is decisive"},
      {word:"submergence",def:"the state of being put under water"},
      {word:"Qu'Appelle River",def:"a large natural stream in Canada"},
      {word:"irrecusable",def:"such that it is not subject to objection or challenge"},
      {word:"stem christie",def:"Sports. a kind of turn made in skiing"},
      {word:"topsy-turvy",def:"in a position so that the upper part is down and the bottom part is up; in a state of total disorder",outside:true},
      {word:"nonchalant",def:"unconcerned; calm and composed"},
      {word:"Peripatetic",def:"(adj.) related to the philosophy of Aristotle | (n.) a follower of this philosophy"},
      {word:"Komodo dragon",def:"a kind of lizard"},
      {word:"superciliary",def:"having to do with the area of the eyebrow; situated over the eye or eyebrow"},
      {word:"Jamaica",def:"an island in the West Indies",outside:true},
      {word:"inculcate",def:"to imbue by repetition; to teach"},
      {word:"luminosity",def:"the condition or quality of shining or glowing"},
      {word:"quaestor",def:"a financial and administrative public official in ancient Rome"},
      {word:"Rhodes scholar",def:"a student who receives a financial grant to attend Oxford University"},
      {word:"surcingle",def:"a girth used to bind something such as a saddle or blanket to a horse"},
      {word:"catechumen",def:"a person being instructed in the principles of Christianity",outside:true},
      {word:"uraeus",def:"the emblem of a serpent used by ancient Egyptian rulers"},
      {word:"revisionary",def:"the work or process of changing or amending something"},
      {word:"umlaut",def:"a diacritical mark",outside:true},
      {word:"unflappable",def:"not easily disturbed or excited; calm"},
      {word:"baleen whale",def:"a large marine mammal"},
      {word:"sensor",def:"a device which receives signals and responds to them"},
      {word:"Ramadan",def:"according to the Muslim calendar, the ninth month; a fast observed during this period"},
      {word:"carcinoma",def:"a kind of tumor",outside:true},
      {word:"revelation",def:"a disclosure; an insight that happens suddenly"},
      {word:"aberrated",def:"having defects or deviations from what one might expect"},
      {word:"vigoroso",def:"Music. with spirit (used as a direction)"},
      {word:"tritanopia",def:"a visual defect causing a person not to be able to discern blue and yellow"},
      {word:"nucleophile",def:"a kind of chemical compound"},
      {word:"impenitent",def:"not contrite or remorseful",outside:true},
      {word:"poinciana",def:"a kind of tree"},
      {word:"intumesce",def:"to enlarge; to bubble up"},
      {word:"keeshond",def:"a kind of dog",outside:true},
      {word:"ornithosis",def:"a disease carried by birds and contracted by humans"},
      {word:"recidivist",def:"one who goes back to a bad behavior, especially criminal behavior"},
      {word:"organically",def:"in a manner derived from living things without the use of synthetics"},
      {word:"oppugned",def:"(past tense) to call something into question",outside:true},
      {word:"misally",def:"to enter unwisely into an association or agreement"},
      {word:"Cassiopeia",def:"a constellation"},
      {word:"lanuginous",def:"covered with hairs like down"},
      {word:"Zapata mustache",def:"hair grown on the upper lip and allowed to curve downward on the sides"},
      {word:"nidicolous",def:"living in the nest until the skill needed to fly is developed (used of birds)"},
      {word:"abbatial",def:"having to do with a kind of monastery or convent"},
      {word:"ytterbium",def:"a metallic element with atomic number 70",outside:true},
      {word:"rhodolite",def:"a variety of garnet"},
      {word:"Cistercian",def:"a member of a monastic order founded in 1098 in France"},
      {word:"viticulture",def:"the growing of grapes"},
      {word:"maelstrom",def:"a chaotic or violent situation; a whirlpool",outside:true},
      {word:"entry-level",def:"appropriate for an inexperienced worker or person"},
      {word:"vinasse",def:"the remaining residue after distillation"},
      {word:"ambit",def:"a boundary; the sphere, scope, or range of something"},
      {word:"ventifact",def:"a stone shaped or polished by sand driven by wind"},
      {word:"expose",def:"the revelation of something that harms a person's reputation; a formal statement of facts"},
      {word:"caseous",def:"like cheese"},
      {word:"yucca",def:"a kind of plant",outside:true}
    ]
  },
  "meet5": {
    name: "Virtual Challenge Meet #5",
    partI: {
      proofreading: [
        {words:["Louis Quatorz","sackcloth","impressionable","cutlery","vibraphone"], answer:"Louis Quatorze"},
        {words:["lebensraum","exiguity","saiga","domesticity","sudoriphic"], answer:"sudorific"},
        {words:["royalism","Erlenmeyer flask","variolate","Syrillic","Monet"], answer:"Cyrillic"},
        {words:["caudate","volunteerism","Sphagnum","multi-lateral","board-certified"], answer:"multilateral"},
        {words:["word processing","indeterminible","epidermis","velleity","newsmagazine"], answer:"indeterminable"},
        {words:["splenomegaly","chorizo","Labrador retriever","pestilential","meletonin"], answer:"melatonin"},
        {words:["mascarpon\u00e9","soup\u00e7on","cerebrate","poltroon","cathect"], answer:"mascarpone"},
        {words:["Stonehenge","prospectus","capitulation","rotogravure","whitepaper"], answer:"white paper"},
        {words:["succussion","altocumulous","ligulate","New Left","obfuscation"], answer:"altocumulus"},
        {words:["eurocentric","ventilator","inadmissible","prix fixe","histology"], answer:"Eurocentric"},
        {words:["mongrelize","afforestation","no-fault","auriferrous","Himalaya Mountains"], answer:"auriferous"},
        {words:["peroral","channelize","Venazuela","ultramundane","replete"], answer:"Venezuela"},
        {words:["sclerous","Pyungyang","untoward","zero hour","concussion"], answer:"Pyongyang"},
        {words:["balaclava","Reconstruction","dystopean","noradrenergic","insidious"], answer:"dystopian"},
        {words:["ide\u00e9 fixe","Ulysses","fortitudinous","chervil","pastina"], answer:"id\u00e9e fixe"}
      ],
      vocabulary: [
        {q:"A mangrove is considered to be _____ because the seedlings emerge from the plant\u2019s fruit to descend into saltwater where the seedlings can then float away to take root any distance from the parent plant.",choices:["fissipalmate","ranula","gentian violet","viviparous","lotus position"],answer:"D"},
        {q:"After observing the small masses and oozing sores on Kyle\u2019s foot, the doctor diagnosed the infection as _____.",choices:["hypnophobia","foramina","scotoma","yersiniosis","mycetoma"],answer:"E"},
        {q:"We were strangely amused by the _____ outfits modeled in the designer fashion show and agreed that very few people would ever wear the bizarre ensembles.",choices:["flagitious","panacean","thrasonical","rumbustious","outr\u00e9"],answer:"E"},
        {q:"The word phantasmagoria is derived from French roots based on _____.",choices:["illusion and allegory","lively and fierce","bell and flower","poem and song","plume and verve"],answer:"A"},
        {q:"The queen was a symbol of _____ as shown in her devoted care and gracious compassion for the underprivileged of her kingdom.",choices:["polynya","benignancy","janissary","equerry","Agincourt"],answer:"B"},
        {q:"Due to evidence of _____, the jurors were moved to give a lighter sentence because they felt the defendant only committed the crime to protect his family from threats made by a local gang member.",choices:["acquittance","cronyism","subornation","eminent domain","anamnesis"],answer:"C"},
        {q:"When the platter of _____ was placed on the table, Shannon took one look at the sea snails and began to feel nauseous at the thought of eating one.",choices:["zwieback","manicotti","cruet","whelk","escarole"],answer:"D"},
        {q:"_____ are also referred to as climbing irons.",choices:["Spangles","Crampons","Menhirs","Dulcimers","Calibrators"],answer:"B"},
        {q:"After injecting a radioactive substance into the veins, the cardiologist was able to observe the _____ of the patient\u2019s circulatory system to verify that it was open and unblocked.",choices:["patency","pleuston","pisciculture","parataxis","prosopography"],answer:"A"},
        {q:"The word _____ is derived from a Latin root meaning \u201ca murmuring.\u201d",choices:["prelapsarian","fremitus","echolocation","cacophonous","wraith"],answer:"B"},
        {q:"_____ is the capital of Syria and one of the oldest continuously inhabited cities in the world.",choices:["Namibia","Quirinal","Ecuador","Damascus","Tophet"],answer:"D"},
        {q:"Archaeologists delicately uncovered the _____ among the ruins, piecing together fragments of its ancient temple.",choices:["reliquiae","timbre","silage","monteith","leachate"],answer:"A"},
        {q:"The speech relied on _____, contrasting freedom and oppression to emphasize the significance of liberty.",choices:["laureate","antithesis","heroic verse","watchword","palindrome"],answer:"B"},
        {q:"The kinesiology undergraduate studied _____ to better understand the structure and function of the human body.",choices:["lycanthropy","exodontics","somatology","thaumatology","pomology"],answer:"C"},
        {q:"Through _____, massive sections of the continent slowly rose and sank over millions of years without major folding or faulting.",choices:["epeirogeny","concrescence","radiolocation","lexicography","escarpment"],answer:"A"}
      ]
    },
    audio: {
      "words1-40": "audio/meet5-words-1-40.mp3",
      "words41-70": "audio/meet5-words-41-70.mp3",
      "tiebreaker": "audio/meet5-tiebreaker-1-20.mp3"
    },
    words: [
      {word:"fluorescence",def:"a type of photoluminous emission"},
      {word:"porcelain",def:"a kind of ceramic; something made of this substance"},
      {word:"myrmecophile",def:"a kind of organism which by habit shares the nest of an ant",outside:true},
      {word:"demolitionist",def:"someone who uses explosives for destructive purposes"},
      {word:"stratigraphy",def:"a field of study related to rocks"},
      {word:"asperse",def:"to malign or spread false charges against a person; to sprinkle as in baptism"},
      {word:"cozenage",def:"deluding or hoodwinking; deception or trickery",outside:true},
      {word:"moraine",def:"an accumulation of the debris such as boulders or stone moved by a glacier"},
      {word:"pellucid",def:"clear or transparent; clear in style as in speech or writing"},
      {word:"leptocephalus",def:"a larva of an eel or related fish"},
      {word:"euxinic",def:"describing an aquatic environment high in hydrogen sulfide and lacking oxygen"},
      {word:"Osceola",def:"a leader of the Seminoles"},
      {word:"entourage",def:"a group of people who serve as attendants; one's surroundings",outside:true},
      {word:"prophesier",def:"a person who speaks of future occurrences as if divinely inspired"},
      {word:"lymphoma",def:"a kind of tumor"},
      {word:"subluxation",def:"partial displacement of a bone from the joint"},
      {word:"convenable",def:"such that it can be summoned or called to meet or appear",outside:true},
      {word:"mummichog",def:"a type of killfish"},
      {word:"khapra beetle",def:"an insect that is very destructive to grain"},
      {word:"laminectomy",def:"a kind of surgery involving the bones of the spinal column"},
      {word:"mignonette",def:"a kind of plant",outside:true},
      {word:"cingulate",def:"having girdlelike markings such as one might see on an animal"},
      {word:"presbyterian",def:"having to do with a kind of church government"},
      {word:"Creutzfeldt-Jakob disease",def:"a kind of ailment affecting the brain"},
      {word:"rhyme royal",def:"a kind of verse form"},
      {word:"fluviomarine",def:"having to do with deposits that were formed by the action of both a river and sea"},
      {word:"poignancy",def:"pathos; tenderness",outside:true},
      {word:"Hegelianism",def:"a philosophy"},
      {word:"serval",def:"a kind of wildcat"},
      {word:"unambiguous",def:"clear"},
      {word:"unctuous",def:"glib or insincere; slippery; made up of or containing oil or fat; rich; soft",outside:true},
      {word:"merriment",def:"fun or cheerfulness"},
      {word:"garbanzo",def:"a kind of plant; the seed produced by this plant"},
      {word:"rubasse",def:"a red quartz"},
      {word:"pityriasis",def:"a kind of skin disease",outside:true},
      {word:"helical",def:"coiled or ringed in shape"},
      {word:"quillwork",def:"articles, made by Native Americans, which had an overlay made of spines from porcupines"},
      {word:"emendate",def:"to make corrections in a text"},
      {word:"rendzina",def:"a kind of soil",outside:true},
      {word:"triskaidekaphobia",def:"an extreme, abnormal fear of the number 13"},
      {word:"klutzy",def:"in an awkward manner"},
      {word:"habanera",def:"a kind of dance or the music for the dance"},
      {word:"obliquity",def:"dubious or uncertain conduct; a deviation from a parallel or perpendicular position"},
      {word:"reincarnate",def:"to be born again; to appear in a new form"},
      {word:"venue",def:"a location where a meeting or gathering takes place; the location where a trial must be held"},
      {word:"deferment",def:"the act of putting off or postponing; an approved waiver of required military service",outside:true},
      {word:"piccolo",def:"a musical instrument"},
      {word:"tough-minded",def:"resolute or realistic"},
      {word:"Ouija",def:"a trademark used for a board a person might use to seek answers to telepathic or spiritual questions"},
      {word:"Chiang Kai-shek",def:"a Chinese leader"},
      {word:"anoxia",def:"a low amount or absence of the element required for respiration"},
      {word:"eventuality",def:"something which might happen; a contingency"},
      {word:"aiguillette",def:"a cord that is worn on a military uniform at the shoulder",outside:true},
      {word:"Rabelais",def:"a French writer"},
      {word:"miasma",def:"an atmosphere which is noxious or poisonous"},
      {word:"somniferous",def:"such that it induces sleep"},
      {word:"geländesprung",def:"a kind of jump made in skiing",alt:"gelandesprung"},
      {word:"reptilian",def:"relating to or like a snake or lizard"},
      {word:"Maori",def:"one of a people of New Zealand; the language of these people"},
      {word:"nauseant",def:"inducing vomiting",outside:true},
      {word:"Tiki",def:"in Polynesian mythology, a male figure identified as the first man"},
      {word:"dilatation",def:"the act of widening an opening"},
      {word:"O'Keeffe",def:"an American painter"},
      {word:"Vatican",def:"the residence of the pope; the papacy",outside:true},
      {word:"Midrash",def:"Jewish commentaries dealing with Hebrew Scriptures"},
      {word:"extraordinaire",def:"very unusual or rare"},
      {word:"triceps",def:"a muscle that runs along the back of the upper arm"},
      {word:"gimlet-eyed",def:"having very good or sharp vision"},
      {word:"tusche",def:"a black liquid which is used in lithography for drawing and is used in silk-screen work and etching as a resist",outside:true},
      {word:"euryphagous",def:"feeding on or eating a variety of foods"}
    ],
    tiebreaker: [
      {word:"constrictor",def:"a muscle that compresses or narrows a passage; a kind of snake"},
      {word:"Wicca",def:"a pagan religion; a group of people who follow this religion"},
      {word:"Molokai",def:"an island in Hawaii",alt:"Moloka'i"},
      {word:"heinously",def:"in a very reprehensible manner",outside:true},
      {word:"languidly",def:"in a weak, listless, or slow manner"},
      {word:"Rayleigh wave",def:"a kind of seismic surface movement"},
      {word:"Hebraic",def:"related to the Jews, their language, or culture"},
      {word:"grotto",def:"a cave; a structure made to resemble a cave"},
      {word:"chaise longue",def:"a kind of seat",outside:true},
      {word:"Ordovician",def:"having to do with a geologic period; a geologic period"},
      {word:"lyophilize",def:"to freeze dry a biological substance"},
      {word:"ptyalism",def:"extreme or excessive flow of saliva"},
      {word:"struthious",def:"having to do with or like an ostrich or other such bird"},
      {word:"carabiner",def:"a device used in mountain climbing",alt:"karabiner"},
      {word:"disembogue",def:"to flow out; to pour forth",outside:true},
      {word:"cosmology",def:"an area of study which centers on the universe"},
      {word:"pasqueflower",def:"a kind of plant"},
      {word:"Salzburg",def:"a city in Austria"},
      {word:"malodor",def:"a foul smell or stench"},
      {word:"incoercible",def:"that which is difficult to control by force",outside:true}
    ]
  }
};

// Function to analyze word morphology (prefixes/suffixes)
function analyzeWord(word) {
  const lower = word.toLowerCase().replace(/[^a-z-]/g, '');
  const result = { prefixes: [], suffixes: [], root: lower };

  // Check prefixes
  const sortedPrefixes = Object.keys(PREFIXES).sort((a, b) => b.length - a.length);
  for (const prefix of sortedPrefixes) {
    const clean = prefix.replace('-', '');
    if (lower.startsWith(clean) && lower.length > clean.length + 2) {
      result.prefixes.push({ prefix: prefix, meaning: PREFIXES[prefix] });
      result.root = lower.slice(clean.length);
      break;
    }
  }

  // Check suffixes
  const sortedSuffixes = Object.keys(SUFFIXES).sort((a, b) => b.length - a.length);
  for (const suffix of sortedSuffixes) {
    const clean = suffix.replace('-', '');
    if (lower.endsWith(clean) && lower.length > clean.length + 2) {
      result.suffixes.push({ suffix: suffix, meaning: SUFFIXES[suffix] });
      result.root = result.root.slice(0, result.root.length - clean.length);
      break;
    }
  }

  return result;
}

// Vocabulary fill-in-the-blank questions from UIL meets
var VOCAB_QUESTIONS = [
  // Meet #1
  {sentence:"The botanist noted that the leaf's surface was distinctly _____, giving it a soft, silvery sheen under the microscope.",options:["sericeous","bagasse","acaulescent","multilateral","cephalic"],answer:"sericeous"},
  {sentence:"In early medicine, physicians often relied on _____ to seal wounds and reduce the risk of infection before the advent of antiseptics.",options:["inoculation","patency","ingesta","cauterization","osteopathy"],answer:"cauterization"},
  {sentence:"The brilliant red color seen in fireworks displays is commonly produced by compounds of _____.",options:["gentian violet","vinasse","bergamot","rhodolite","strontium"],answer:"strontium"},
  {sentence:"During the 2020 pandemic, many experts in _____ were consulted to devise a plan to get the nation's workforce reactivated.",options:["pomology","macroeconomics","antipersonnel","exodontics","subornation"],answer:"macroeconomics"},
  {sentence:"After the Apollo missions returned lunar rock samples, the field of _____ expanded rapidly as scientists analyzed the Moon's geology.",options:["selenology","prosopography","thaumatology","somatology","biostatistics"],answer:"selenology"},
  {sentence:"At the Scandinavian food festival, visitors enjoyed slices of _____ paired with crisp bread and fruit preserves.",options:["en brochette","mulligatawny","Jarlsberg","tantara","brio"],answer:"Jarlsberg"},
  {sentence:"The veterinarian _____ the feral cat so that she could safely provide care for the frantic feline.",options:["vaticinated","queued","sedated","lyophilized","amalgamated"],answer:"sedated"},
  {sentence:"Gauntness and degeneration are synonymous with _____.",options:["escarpment","afforestation","obfuscation","acquittance","emaciation"],answer:"emaciation"},
  {sentence:"Known worldwide for his exquisite work with gems, the _____ was asked to prepare rubies and emeralds for a royal crown.",options:["equerry","lapidarian","quadrumvirate","poltroon","wainwright"],answer:"lapidarian"},
  {sentence:"Unlike precocial chicks that wander almost immediately, robins are _____ and remain in the nest for weeks.",options:["motile","rupicolous","viviparous","nidicolous","valgus"],answer:"nidicolous"},
  {sentence:"The surgeon explained that the knee joint is formed in part by the femur's medial _____.",options:["fremitus","sternocleidomastoid","condyle","amphorae","coccyx"],answer:"condyle"},
  {sentence:"The judge gave a harsher sentence because the defendant was a known _____ with multiple prior convictions.",options:["recidivist","librettist","sluggard","nabob","genealogist"],answer:"recidivist"},
  {sentence:"On summer mornings, a sky dotted with _____ clouds can signal unsettled weather later in the day.",options:["auriferous","harmattan","prelapsarian","sylvatic","altocumulus"],answer:"altocumulus"},
  {sentence:"In 17th-century European armies, a _____ was originally tasked with throwing small explosive bombs by hand.",options:["festschrift","dynamo","swashbuckler","grenadier","janissary"],answer:"grenadier"},
  {sentence:"The court ordered the burglar to pay full _____ to the store for the stolen merchandise.",options:["rapprochement","restitution","exemplum","salience","commination"],answer:"restitution"},
  // Meet #2
  {sentence:"The poor librarian was traumatized by the thunderous _____ caused by thousands of books crashing to the hardwood floor as several bookcases toppled like dominoes.",options:["taradiddle","farandole","altercation","reverie","bouleversement"],answer:"bouleversement"},
  {sentence:"The epidemiologist studied the _____ diseases transmitted by biological vectors such as flies and rodents.",options:["pestilential","potable","cephalic","ethereal","unwonted"],answer:"pestilential"},
  {sentence:"We received many _____ cards after our grandmother passed away.",options:["tenuous","refulgent","condolatory","prefatory","nuncupative"],answer:"condolatory"},
  {sentence:"The word _____ is derived from Breton roots meaning 'stone' and 'long.'",options:["nabob","mukluk","Bauhaus","keffiyeh","menhir"],answer:"menhir"},
  {sentence:"In traditional Indian dress, a colorful _____ often accompanies a sherwani or formal tunic.",options:["janissary","cummerbund","langlauf","mal de mer","quondam"],answer:"cummerbund"},
  {sentence:"Boastful and bragging are synonymous with _____.",options:["rumbustious","siccative","incommodious","thrasonical","efficacious"],answer:"thrasonical"},
  {sentence:"The _____ monks are known for their devotion to manual labor, silence, and simple living.",options:["dystopian","Cistercian","librettist","Tophet","Rotarian"],answer:"Cistercian"},
  {sentence:"The stop-and-go traffic on the scorching highway and no air conditioner in the car made the commute absolutely _____.",options:["torturous","pellucid","infinitesimal","cacophonous","flagitious"],answer:"torturous"},
  {sentence:"Because of its location on the equator in South America, _____ experiences roughly equal hours of daylight and night year-round.",options:["Zululand","Bataan","Ecuador","Damascus","Saarland"],answer:"Ecuador"},
  {sentence:"The violinist used a graceful _____ to connect the two notes seamlessly during the solo.",options:["dulcimer","tantara","subito","paisano","portamento"],answer:"portamento"},
  {sentence:"Emails and messages _____ in her inbox, each demanding her attention.",options:["spangled","queued","ceded","repined","emendated"],answer:"queued"},
  {sentence:"In team projects, being _____ helps ensure that everyone understands the goals and responsibilities.",options:["communicative","abbatial","peccant","fiducial","expeditionary"],answer:"communicative"},
  {sentence:"In the Alps, herders practice _____ by leading cattle uphill in summer and back to the valleys in winter.",options:["harmattan","echolocation","eminent domain","transhumance","acculturation"],answer:"transhumance"},
  {sentence:"The Romans advanced _____ throughout Europe, laying the foundation for many of today's famous wine regions.",options:["lexicography","obfuscation","brusquerie","viticulture","escarpment"],answer:"viticulture"},
  {sentence:"The _____ is unique among marsupials because both males and females have watertight pouches for swimming.",options:["faun","red herring","yapok","serval","zebu"],answer:"yapok"},
  // Meet #3
  {sentence:"The _____ shape of the moon almost looked like the blade of a sickle.",options:["mandala","falcate","multilateral","arborescent","tenuous"],answer:"falcate"},
  {sentence:"The noun _____ is derived from the Old French root meaning 'peasant.'",options:["panacean","paisano","praenomen","pleuston","portiere"],answer:"paisano"},
  {sentence:"The _____ bones in her foot were caused from years of wearing ill-fitting shoes.",options:["cephalic","organoleptic","valgus","sylvatic","diatomaceous"],answer:"valgus"},
  {sentence:"The tour guide explained that the _____ residence belonged to the head of the monastery.",options:["manorial","coadunate","dystopian","abbatial","histrionic"],answer:"abbatial"},
  {sentence:"The _____ was far too steep to climb without special equipment.",options:["aquifer","escarpment","condyle","equerry","polynya"],answer:"escarpment"},
  {sentence:"The sizable antlers of the male _____ may tower four feet above his head.",options:["mandrill","whelk","wapiti","guillemot","serval"],answer:"wapiti"},
  {sentence:"As the old lady was mugged, the _____ gawked or walked away and did nothing to help protect her from her attackers.",options:["gadflies","prima donnas","grenadiers","nabobs","poltroons"],answer:"poltroons"},
  {sentence:"The powerful aroma of burgers on the grill was _____ in attracting customers to the food truck.",options:["efficacious","quondam","tenebrific","enigmatical","auriferous"],answer:"efficacious"},
  {sentence:"Synonymous with _____ are slogan and shibboleth.",options:["underpinning","langlauf","brio","watchword","exemplum"],answer:"watchword"},
  {sentence:"The artist's paintings were considered _____ because they depicted skeletons, shadows, and scenes of death in unsettling detail.",options:["macabre","antipersonnel","incommodious","circumspect","apocalyptic"],answer:"macabre"},
  {sentence:"In public health studies, _____ is often discussed as a foodborne disease that can mimic appendicitis in children.",options:["mal de mer","ranula","yersiniosis","scotoma","deuteranopia"],answer:"yersiniosis"},
  {sentence:"As we entered the gym, we were overwhelmed with the _____ sounds of the exercise machines and heavy weights reverberating as they collided.",options:["apatetic","flagitious","ethereal","peccant","cacophonous"],answer:"cacophonous"},
  {sentence:"Ancient oracles were believed to _____ future events through prophecy and divine insight.",options:["repine","vaticinate","amalgamate","deploy","lyophilize"],answer:"vaticinate"},
  {sentence:"_____ is a country located on the southern edge of the Arabian Peninsula, bordered by Saudi Arabia and Oman.",options:["Namibia","Bataan","Damascus","Yemen","Zululand"],answer:"Yemen"},
  {sentence:"The _____ in western Africa created a haze that limited visibility and partially blocked sunlight.",options:["harmattan","yurt","bergamot","silage","tantara"],answer:"harmattan"},
  // Meet #4
  {sentence:"Medication helped reduce his _____ during the rough ocean crossing.",options:["mal de mer","anamnesis","yersiniosis","scotoma","valgus"],answer:"mal de mer"},
  {sentence:"The villagers whispered that a _____ haunted the old road, appearing on foggy nights as a sign of death.",options:["tantara","wraith","brusquerie","pleuston","reverie"],answer:"wraith"},
  {sentence:"Incorporating obviously staged and scripted drama, many 'reality' shows rely on the _____ to believe that these ridiculous performances are actual events.",options:["rime riche","opera bouffe","Fascisti","pisciculture","booboisie"],answer:"booboisie"},
  {sentence:"After dropping her phone in the swimming pool, Linda placed the device in a container filled with rice hoping it would _____ it.",options:["cathect","emendate","tergiversate","desiccate","amalgamate"],answer:"desiccate"},
  {sentence:"Ian pursued a degree in botany focusing on the _____ of citrus fruits.",options:["exodontics","methodology","somatology","pomology","stichometry"],answer:"pomology"},
  {sentence:"The word _____ originates from a Latin root meaning 'to grow together.'",options:["concrescence","leachate","arborescent","festschrift","escarpment"],answer:"concrescence"},
  {sentence:"_____ gained independence from South Africa in 1990.",options:["Saarland","Yemen","Namibia","Quirinal","Damascus"],answer:"Namibia"},
  {sentence:"A _____ uses its height and sharp hearing to hunt rodents in tall grass.",options:["rhesus monkey","serval","guillemot","zebu","whelk"],answer:"serval"},
  {sentence:"Ancient Greeks used _____ to store and transport wine, oil, and grain.",options:["crampons","gimmals","silage","portiere","amphorae"],answer:"amphorae"},
  {sentence:"The theory of thesis, antithesis, and synthesis is commonly associated with _____.",options:["phantasmagoria","rapprochement","Hegelianism","Midrash","obfuscation"],answer:"Hegelianism"},
  {sentence:"The campsite offered guests the chance to stay overnight in a modern _____.",options:["Bauhaus","yurt","mandala","palindrome","keffiyeh"],answer:"yurt"},
  {sentence:"The judges discussed the matter _____ before announcing their decision publicly.",options:["nefariously","metabolically","subito","inter se","counterfactual"],answer:"inter se"},
  {sentence:"Synonymous with _____ would be diaphanous and celestial.",options:["ethereal","unwonted","apocalyptic","prelapsarian","nuncupative"],answer:"ethereal"},
  {sentence:"Mosquitoes thrive in _____ areas where wetlands and swamps are common.",options:["rupicolous","cismontane","paludal","auriferous","fissipalmate"],answer:"paludal"},
  {sentence:"Dandelions are an example of _____ plants, with flowers rising directly from the base rather than a stem.",options:["falcate","acaulescent","scansorial","multilateral","diatomaceous"],answer:"acaulescent"},
  // Generated vocabulary questions (unique words not in original set)
  {sentence:"The concept was so _____ that even graduate students struggled to understand the professor's lecture.",options:["abstruse","propitious","sepulchral","nodose","stodgy"],answer:"abstruse"},
  {sentence:"A distinguished _____ at the university, she had published dozens of papers in peer-reviewed journals.",options:["academician","poetaster","journeyman","huckster","paranoiac"],answer:"academician"},
  {sentence:"The crowd erupted in _____, cheering loudly as the winning goal was scored in the final seconds.",options:["acclamation","commination","protestation","obfuscation","proscription"],answer:"acclamation"},
  {sentence:"Through _____, immigrant families gradually adopted the customs and language of their new country.",options:["acculturation","expansionism","puritanism","objectivism","imperialism"],answer:"acculturation"},
  {sentence:"Her business _____ allowed her to identify profitable opportunities that others overlooked.",options:["acumen","dubiety","vacuity","domesticity","exclusivity"],answer:"acumen"},
  {sentence:"Fat is stored as energy in each _____, which can expand or shrink depending on caloric intake.",options:["adipocyte","monochasium","proventriculus","saccade","kaon"],answer:"adipocyte"},
  {sentence:"The _____ of the defendant's confession was debated heavily by the attorneys on both sides.",options:["admissibility","remuneration","recapitulation","minimization","pronouncement"],answer:"admissibility"},
  {sentence:"Under the _____ of the United Nations, the peacekeeping mission was protected from outside interference.",options:["aegis","parapet","proscription","stricture","importunity"],answer:"aegis"},
  {sentence:"The _____ collector spent years gathering Roman coins and medieval manuscripts for his private museum.",options:["antiquarian","cognoscente","genealogist","thespian","kibbutznik"],answer:"antiquarian"},
  {sentence:"The camera's _____ determines how much light enters the lens and affects the depth of field.",options:["aperture","parameter","ellipsis","saccade","tmesis"],answer:"aperture"},
  {sentence:"The preacher's _____ warnings about the end of the world frightened the congregation.",options:["apocalyptic","apollonian","saccharine","rumbustious","pulmonic"],answer:"apocalyptic"},
  {sentence:"The _____ clarity of Mozart's compositions stood in stark contrast to the emotional chaos of Romantic era music.",options:["apollonian","apocalyptic","sepulchral","dystopian","misanthropic"],answer:"apollonian"},
  {sentence:"The _____ renounced his faith publicly and was expelled from the religious order.",options:["apostate","catechumen","parishioner","nonagenarian","kibbutznik"],answer:"apostate"},
  {sentence:"The manager sent a memo to _____ the staff of the upcoming changes to the holiday schedule.",options:["apprise","expurgate","reify","degauss","lucubrate"],answer:"apprise"},
  {sentence:"The _____ solution was mostly water with a small amount of dissolved mineral salts.",options:["aqueous","terraqueous","pneumatic","phreatic","parabolic"],answer:"aqueous"},
  {sentence:"The region's _____ supplied drinking water to three counties through a vast network of underground wells.",options:["aquifer","exosphere","solfatara","playa","panorama"],answer:"aquifer"},
  {sentence:"The coral formations had an _____ structure, branching outward like the limbs of a miniature tree.",options:["arborescent","ligulate","obovate","nodose","serpiginous"],answer:"arborescent"},
  {sentence:"The miners discovered an _____ vein of ore, rich with silver deposits running deep into the mountain.",options:["argentiferous","melliferous","phytophagous","pulmonic","stomachic"],answer:"argentiferous"},
  {sentence:"The singer performed a beautiful _____, her voice soaring somewhere between recitative and full aria.",options:["arioso","staccato","portamento","piccolo","dulcimer"],answer:"arioso"},
  {sentence:"She quickly _____ to the top of the corporate ladder, eagerly seeking every advancement opportunity.",options:["aspirant","futilitarian","paranoiac","misdemeanant","loggerhead"],answer:"aspirant"},
  {sentence:"A warm cup of tea helped to _____ her anxiety before the big presentation.",options:["assuage","exacerbate","militarize","commandeer","mongrelize"],answer:"assuage"},
  {sentence:"The _____ fur trim on the coat collar gave it a luxurious, old-world elegance.",options:["astrakhan","maillot","parfleche","redingote","vambrace"],answer:"astrakhan"},
  {sentence:"His _____ temperament made him prone to dark moods and bitter complaints about everything.",options:["atrabilious","propitious","effulgent","uninhibited","nonchalant"],answer:"atrabilious"},
  {sentence:"The monk studied Buddhism intensely, hoping one day to follow the path of the _____.",options:["bodhisattva","tetrarch","kapellmeister","shaitan","sherpa"],answer:"bodhisattva"},
  {sentence:"The _____ sizzled on the grill at the Oktoberfest celebration, filling the tent with a savory aroma.",options:["bratwurst","chorizo","garbanzo","pierogi","gigot"],answer:"bratwurst"},
  {sentence:"The priest read from the _____, reciting the daily prayers and hymns for the canonical hours.",options:["breviaries","psalter","novena","kaddish","shekhinah"],answer:"breviaries"},
  {sentence:"The conductor led the orchestra with great _____, infusing every passage with vivid energy.",options:["brio","timbre","staccato","arioso","tmesis"],answer:"brio"},
  {sentence:"His _____ reply offended the guests, as they had expected a warmer welcome from the host.",options:["brusquerie","politesse","deference","collegiality","domesticity"],answer:"brusquerie"},
  {sentence:"The additional regulations made the permitting process more _____ for small business owners.",options:["burdensome","extensible","separable","impracticable","user-friendly"],answer:"burdensome"},
  {sentence:"The polished _____ gemstone shimmered with a smooth, domed surface instead of the usual faceted cut.",options:["cabochon","astrakhan","tiki","steppingstone","drogue"],answer:"cabochon"},
  {sentence:"Tropical trees are tapped for _____, which is processed into natural rubber for industrial use.",options:["caoutchouc","glycogen","hydrazine","leachate","eiderdown"],answer:"caoutchouc"},
  {sentence:"The pregnant woman developed _____, noticeable as yellowish-brown patches on her cheeks and forehead.",options:["chloasma","paresthesia","splenomegaly","microcephaly","paraplegia"],answer:"chloasma"},
  {sentence:"The spicy _____ added a smoky heat to the Spanish rice and bean dish.",options:["chorizo","bratwurst","garbanzo","pierogi","gigot"],answer:"chorizo"},
  {sentence:"The historian _____ the events of the revolution in meticulous detail for future generations.",options:["chronicled","philosophized","procrastinated","democratized","unionized"],answer:"chronicled"},
  {sentence:"It took considerable _____ for the young entrepreneur to pitch her idea to a room full of skeptical investors.",options:["chutzpah","deference","dubiety","domesticity","collegiality"],answer:"chutzpah"},
  {sentence:"The French word uses a _____ accent over the letter 'e' to indicate a change in pronunciation.",options:["circumflex","umlaut","ellipsis","palindrome","pangram"],answer:"circumflex"},
  {sentence:"A _____ leader considers all perspectives and potential consequences before making an important decision.",options:["circumspect","rumbustious","uninhibited","stodgy","impressionable"],answer:"circumspect"},
  {sentence:"The ancient Greeks used a _____ to measure time by the regulated flow of water through a small opening.",options:["clepsydra","hygrometer","magnetometer","defibrillator","micropipette"],answer:"clepsydra"},
  {sentence:"Damage to the _____ bone at the base of the spine can cause significant pain when sitting.",options:["coccyx","olecranon","gladiolus","septa","sacroiliac"],answer:"coccyx"},
  {sentence:"Sound vibrations travel through the spiral-shaped _____ in the inner ear, where they are converted to nerve signals.",options:["cochlea","proventriculus","rhinencephalon","sternocleidomastoid","coccyx"],answer:"cochlea"},
  {sentence:"As a true _____ of fine wine, he could identify the vineyard and vintage with just one sip.",options:["cognoscente","poetaster","huckster","junketeer","futilitarian"],answer:"cognoscente"},
  {sentence:"The department valued _____, with faculty members working cooperatively on research projects.",options:["collegiality","exclusivity","importunity","expansionism","puritanism"],answer:"collegiality"},
  {sentence:"The guest speaker presented her findings at the university _____, followed by a lively discussion.",options:["colloquium","panorama","prospectus","psalter","festschrift"],answer:"colloquium"},
  {sentence:"The soldiers were ordered to _____ the civilian vehicles for use in evacuating the flood zone.",options:["commandeer","philosophize","lucubrate","gormandize","degauss"],answer:"commandeer"},
  {sentence:"The pastor delivered a stern _____, warning the congregation of divine punishment for their wrongdoing.",options:["commination","plaudit","pronouncement","protestation","recommendation"],answer:"commination"},
  {sentence:"_____ is the inability to distinguish red from green, the most common form of color blindness.",options:["daltonism","protanopia","tritanopia","deuteranopia","scotoma"],answer:"daltonism"},
  {sentence:"The weed known as _____ grows among wheat fields and can be toxic if consumed in large quantities.",options:["darnel","selaginella","echeveria","asparagus","poinciana"],answer:"darnel"},
  {sentence:"The _____ nobleman wasted his fortune on lavish parties and reckless pleasures.",options:["debauched","circumspect","monastic","puritanical","propitious"],answer:"debauched"},
  {sentence:"After the rescue mission, the team underwent a thorough _____ with intelligence officers.",options:["debriefing","arraignment","colloquium","validation","recruitment"],answer:"debriefing"},
  {sentence:"She practiced the art of _____, carefully gluing cutout images onto a wooden jewelry box.",options:["decoupage","rotogravure","iconography","stratigraphy","impressionism"],answer:"decoupage"},
  {sentence:"The government decided to _____ authority, transferring power from the capital to regional offices.",options:["decentralize","militarize","reincarnate","unionize","mongrelize"],answer:"decentralize"},
  {sentence:"The spy needed to _____ the intercepted message before its contents could be understood.",options:["decrypt","degauss","reify","economize","expurgate"],answer:"decrypt"},
  {sentence:"Negotiators worked to _____ the conflict before it could spiral into a full military confrontation.",options:["de-escalate","exacerbate","commandeer","militarize","procrastinate"],answer:"de-escalate"},
  {sentence:"Out of _____ for the elder professor, the students stood when she entered the lecture hall.",options:["deference","chutzpah","brusquerie","importunity","dubiety"],answer:"deference"},
  {sentence:"The paramedic used a portable _____ to restore the patient's heart rhythm after cardiac arrest.",options:["defibrillator","hygrometer","magnetometer","micropipette","clepsydra"],answer:"defibrillator"},
  {sentence:"Widespread _____ in the Amazon basin has contributed to climate change and loss of biodiversity.",options:["deforestation","acculturation","reconstruction","rejuvenescence","liquefaction"],answer:"deforestation"},
  {sentence:"The technician had to _____ the old computer monitor to eliminate the distorted colors on the screen.",options:["degauss","decrypt","reify","expurgate","fructify"],answer:"degauss"},
  {sentence:"Running the _____ in the basement helped reduce moisture levels and prevent mold growth.",options:["dehumidify","weatherize","economize","recalculate","philosophize"],answer:"dehumidify"},
  {sentence:"Efforts to _____ the country's government included introducing free elections and a free press.",options:["democratize","militarize","unionize","mongrelize","decentralize"],answer:"democratize"},
  {sentence:"The famous _____ signed autographs after the sold-out concert at the opera house.",options:["diva","thespian","poetaster","aspirant","cognoscente"],answer:"diva"},
  {sentence:"The school celebrated _____ week with events honoring students from many different cultural backgrounds.",options:["diversity","exclusivity","domesticity","collegiality","admissibility"],answer:"diversity"},
  {sentence:"Ancient cultures practiced _____, using the stars, bones, and animal entrails to predict the future.",options:["divination","psychogenesis","reflexology","iconography","stratigraphy"],answer:"divination"},
  {sentence:"After years of traveling, she found comfort in the quiet _____ of raising a family in a small town.",options:["domesticity","diversity","exclusivity","importunity","collegiality"],answer:"domesticity"},
  {sentence:"The party's propaganda relied on _____, getting citizens to accept contradictory ideas simultaneously.",options:["doublethink","parataxis","prolepsis","tmesis","subaudition"],answer:"doublethink"},
  {sentence:"A _____ was attached to the harpoon line to slow the whale and prevent it from diving too deep.",options:["drogue","oarlock","plunger","vambrace","surcingle"],answer:"drogue"},
  {sentence:"He expressed _____ about the plan's chances of success, uncertain whether it could actually work.",options:["dubiety","acumen","deference","brio","chutzpah"],answer:"dubiety"},
  {sentence:"The _____ hammered gently, its bright metallic tones filling the small concert hall with resonant sound.",options:["dulcimer","piccolo","woofer","shofar","saxophone"],answer:"dulcimer"},
  {sentence:"The two consuls served together in a _____, sharing executive power equally during their term.",options:["duumvirate","colloquium","papacy","quadrennium","chiliad"],answer:"duumvirate"},
  {sentence:"The _____ generator at the hydroelectric plant converts mechanical energy into electricity for the grid.",options:["dynamo","sensor","magnetometer","defibrillator","hygrometer"],answer:"dynamo"},
  {sentence:"Chronic _____ caused him to avoid spicy foods and always keep antacids on hand.",options:["dyspepsia","paresthesia","psychosis","paraplegia","splenomegaly"],answer:"dyspepsia"},
  {sentence:"The novel depicted a _____ society where citizens were surveilled constantly and free speech was forbidden.",options:["dystopian","apollonian","propitious","monastic","sepulchral"],answer:"dystopian"},
  {sentence:"His devotion to _____ led him to insist that traditional church ceremonies never be modernized.",options:["ecclesiasticism","unilateralism","expansionism","objectivism","puritanism"],answer:"ecclesiasticism"},
  {sentence:"The succulent garden featured a stunning arrangement of _____ plants with rosette-shaped leaves.",options:["echeveria","selaginella","asparagus","darnel","poinciana"],answer:"echeveria"},
  {sentence:"Bats navigate in complete darkness using _____, emitting high-frequency sounds that bounce off objects.",options:["echolocation","divination","reflexology","psychogenesis","stratigraphy"],answer:"echolocation"},
  {sentence:"To _____ on household expenses, she started meal planning and buying groceries in bulk.",options:["economize","gormandize","procrastinate","commandeer","lucubrate"],answer:"economize"},
  {sentence:"The old house at night was the _____ place they had ever visited, with creaking floors and strange shadows.",options:["eeriest","propitious","effulgent","rumbustious","saccharine"],answer:"eeriest"},
  {sentence:"The sunset cast an _____ glow across the lake, bathing everything in warm golden light.",options:["effulgent","sepulchral","atrabilious","dystopian","stodgy"],answer:"effulgent"},
  {sentence:"The fluffy _____ comforter kept them warm through even the coldest winter nights.",options:["eiderdown","astrakhan","maillot","parfleche","sackcloth"],answer:"eiderdown"},
  {sentence:"The poet was asked to _____ the fallen soldiers in verse at the memorial ceremony.",options:["elegize","vaccinate","reincarnate","genuflect","gormandize"],answer:"elegize"},
  {sentence:"The British office tradition of _____ gave everyone a chance to have tea and biscuits mid-morning.",options:["elevenses","shabbat","novena","tete-a-tete","colloquium"],answer:"elevenses"},
  {sentence:"The author used an _____ to indicate that several words had been deliberately omitted from the quotation.",options:["ellipsis","circumflex","umlaut","palindrome","pangram"],answer:"ellipsis"},
  {sentence:"The church elder spoke out in an _____ sermon, urging the community to return to the teachings of the Gospel.",options:["evangelical","monastic","liturgical","ecclesiastic","sepulchral"],answer:"evangelical"},
  {sentence:"An _____ is a gravitational modification of the lunar orbit caused by the pull of the Sun.",options:["evection","advection","saccade","prolepsis","subaudition"],answer:"evection"},
  {sentence:"We packed emergency supplies in case of any _____, from severe storms to power outages.",options:["eventuality","pronouncement","recommendation","reconstruction","recapitulation"],answer:"eventuality"},
  {sentence:"Skipping the inspection would only _____ the existing structural problems in the old building.",options:["exacerbate","assuage","mitigate","dehumidify","economize"],answer:"exacerbate"},
  {sentence:"The country club's _____ made it difficult for newcomers to gain membership.",options:["exclusivity","diversity","domesticity","collegiality","admissibility"],answer:"exclusivity"},
  {sentence:"The senator used a biblical _____ to illustrate the moral lesson he was trying to convey.",options:["exemplum","palindrome","pangram","kenning","illative"],answer:"exemplum"},
  {sentence:"Satellites orbiting in the _____ experience almost no atmospheric drag due to the extremely thin gas layer.",options:["exosphere","aquifer","panorama","playa","stratigraphy"],answer:"exosphere"},
  {sentence:"The nation's aggressive _____ in the region led to tensions with its neighboring countries.",options:["expansionism","puritanism","objectivism","ecclesiasticism","unilateralism"],answer:"expansionism"},
  {sentence:"The publisher decided to _____ the offensive passages from the new edition of the classic novel.",options:["expurgate","decrypt","reify","degauss","lucubrate"],answer:"expurgate"},
  {sentence:"The software framework was designed to be _____, allowing developers to add new modules easily.",options:["extensible","impracticable","separable","pneumatic","parabolic"],answer:"extensible"},
  {sentence:"She was a chef _____, famous throughout the country for her innovative approach to pastry.",options:["extraordinaire","monastic","sepulchral","rumbustious","impromptu"],answer:"extraordinaire"},
  {sentence:"The firefighters worked for hours to _____ the driver from the mangled wreckage of the car.",options:["extricate","commandeer","militarize","degauss","expurgate"],answer:"extricate"},
  {sentence:"The general adopted a _____ strategy, avoiding direct battle and instead wearing down the enemy through attrition.",options:["fabian","expeditionary","prosecutorial","regressive","recurrent"],answer:"fabian"},
  {sentence:"The investment was expected to _____ in the second year, finally producing returns for the shareholders.",options:["fructify","procrastinate","lucubrate","gormandize","degauss"],answer:"fructify"},
  {sentence:"The _____ believed that no human effort could ever produce lasting meaning or change in the world.",options:["futilitarian","aspirant","cognoscente","paranoiac","antiquarian"],answer:"futilitarian"},
  {sentence:"The pesky _____ kept buzzing around the cattle, irritating the herd and spreading disease.",options:["gadfly","whelk","wombat","sturgeon","saiga"],answer:"gadfly"},
  {sentence:"The recipe called for a cup of cooked _____ beans, also known as chickpeas.",options:["garbanzo","chorizo","bratwurst","pierogi","gigot"],answer:"garbanzo"},
  {sentence:"It was a _____ suburban house with nothing remarkable about it — completely ordinary in every way.",options:["garden-variety","world-shaking","extraordinaire","ill-fated","untoward"],answer:"garden-variety"},
  {sentence:"The professional _____ traced his family tree back twelve generations to a small village in Ireland.",options:["genealogist","antiquarian","cognoscente","poetaster","thespian"],answer:"genealogist"},
  {sentence:"The doctor applied _____ to the wound as an antiseptic, leaving a vivid purple stain on the skin.",options:["gentian violet","lidocaine","hydrazine","glycogen","caoutchouc"],answer:"gentian violet"},
  {sentence:"The worshippers would _____ upon entering the cathedral, bending one knee as a sign of reverence.",options:["genuflect","procrastinate","philosophize","lucubrate","gormandize"],answer:"genuflect"},
  {sentence:"The butcher prepared a roasted _____ of lamb seasoned with garlic, rosemary, and thyme.",options:["gigot","bratwurst","chorizo","garbanzo","pierogi"],answer:"gigot"},
  {sentence:"The center part of the sternum is anatomically referred to as the _____.",options:["gladiolus","coccyx","cochlea","olecranon","septa"],answer:"gladiolus"},
  {sentence:"The party was filled with _____ — movie stars, tech billionaires, and fashion designers mingling under crystal chandeliers.",options:["glitterati","booboisie","poltroons","gadflies","poetasters"],answer:"glitterati"},
  {sentence:"The body converts excess glucose into _____, which is stored in the liver and muscles for later energy use.",options:["glycogen","hydrazine","caoutchouc","lidocaine","kaon"],answer:"glycogen"},
  {sentence:"He would _____ at the buffet, piling his plate high and going back for thirds without any restraint.",options:["gormandize","economize","genuflect","procrastinate","philosophize"],answer:"gormandize"},
  {sentence:"The _____ peddler went door to door selling cheap household goods and trinkets.",options:["huckster","cognoscente","antiquarian","thespian","journeyman"],answer:"huckster"},
  {sentence:"The public _____ of the losing team's coach was captured on camera for the entire nation to see.",options:["humiliation","acclamation","protestation","pronouncement","validation"],answer:"humiliation"},
  {sentence:"_____ is used as rocket fuel because of its powerful reactivity when combined with an oxidizer.",options:["hydrazine","glycogen","caoutchouc","lidocaine","eiderdown"],answer:"hydrazine"},
  {sentence:"The _____ studied the underground water systems to determine whether the aquifer could sustain the new development.",options:["hydrogeology","stratigraphy","reflexology","iconography","psychogenesis"],answer:"hydrogeology"},
  {sentence:"The scientist used a _____ to measure the relative humidity inside the climate-controlled storage facility.",options:["hygrometer","magnetometer","defibrillator","micropipette","clepsydra"],answer:"hygrometer"},
  {sentence:"_____ is the philosophical doctrine that all matter possesses some form of life or consciousness.",options:["hylozoism","objectivism","puritanism","ecclesiasticism","expansionism"],answer:"hylozoism"},
  {sentence:"The professor posed a _____ scenario to test how students would apply the legal principles they had learned.",options:["hypothetical","parabolic","extensible","pneumatic","liturgical"],answer:"hypothetical"},
  {sentence:"The fossil had clearly _____ features, resembling a fish more than any land-dwelling creature.",options:["ichthyic","theriomorphic","piscine","simian","phytophagous"],answer:"ichthyic"},
  {sentence:"The museum's exhibit on religious _____ showcased symbolic imagery from cultures around the world.",options:["iconography","stratigraphy","reflexology","hydrogeology","impressionism"],answer:"iconography"},
  {sentence:"The philosopher's argument was entirely _____, meaning the conclusion was drawn from the premises by reasoning alone.",options:["illative","extensible","impracticable","regressive","recurrent"],answer:"illative"},
  {sentence:"The _____ voyage of the Titanic ended in one of the worst maritime disasters in history.",options:["ill-fated","propitious","effulgent","rumbustious","garden-variety"],answer:"ill-fated"},
  {sentence:"The divine was described as _____, present throughout all of creation rather than existing separately from it.",options:["immanent","immemorial","unremitting","impressionable","uninhibited"],answer:"immanent"},
  {sentence:"The tradition stretched back to a time _____, long before anyone could remember its origins.",options:["immemorial","immanent","hypothetical","extensible","impracticable"],answer:"immemorial"},
  {sentence:"Only _____ individuals can receive live vaccines safely; those with weakened immune systems cannot.",options:["immunocompetent","imperceptive","impressionable","uninhibited","nonexistent"],answer:"immunocompetent"},
  {sentence:"The negotiations reached an _____ when neither side was willing to make any further concessions.",options:["impasse","aperture","ellipsis","stricture","panorama"],answer:"impasse"},
  {sentence:"The country's aggressive _____ in the 19th century led to the colonization of vast territories overseas.",options:["imperialism","expansionism","unilateralism","puritanism","objectivism"],answer:"imperialism"},
  {sentence:"His constant _____ for a raise finally wore down his manager, who agreed just to stop the asking.",options:["importunity","deference","dubiety","domesticity","collegiality"],answer:"importunity"},
  {sentence:"Building the bridge in three months was simply _____ given the limited budget and workforce.",options:["impracticable","extensible","separable","hypothetical","user-friendly"],answer:"impracticable"},
  {sentence:"The young, _____ teenager was easily swayed by social media trends and peer pressure.",options:["impressionable","unremitting","immunocompetent","imperceptive","circumspect"],answer:"impressionable"},
  {sentence:"The museum's _____ gallery featured paintings by Monet, Renoir, and Degas that emphasized light and color.",options:["impressionism","iconography","stratigraphy","reflexology","hydrogeology"],answer:"impressionism"},
  {sentence:"The comedian delivered a hilariously _____ speech that she clearly had not prepared in advance.",options:["impromptu","hypothetical","parabolic","liturgical","extensible"],answer:"impromptu"},
  {sentence:"The stone _____ stood on the Arctic tundra, a human-shaped landmark built by the Inuit centuries ago.",options:["inukshuk","menhir","tiki","steppingstone","ventifact"],answer:"inukshuk"},
  {sentence:"The damage caused by the oil spill was _____, leaving the coastline permanently scarred.",options:["irremediable","separable","extensible","impracticable","user-friendly"],answer:"irremediable"},
  {sentence:"After a long day of hiking, they soaked in the warm _____ at the resort, letting the jets soothe their sore muscles.",options:["jacuzzi","plunger","oarlock","drogue","clepsydra"],answer:"jacuzzi"},
  {sentence:"The _____ soldiers of the Ottoman Empire were once among the most feared warriors in the world.",options:["janissary","grenadier","expeditionary","fabian","monastic"],answer:"janissary"},
  {sentence:"Travelers crossing multiple time zones often suffer from _____, feeling exhausted and disoriented for days.",options:["jet lag","nitrogen narcosis","paraplegia","dyspepsia","paresthesia"],answer:"jet lag"},
  {sentence:"The politician was accused of _____, using his office to award contracts to friends and family for personal gain.",options:["jobbery","chutzpah","importunity","brusquerie","dubiety"],answer:"jobbery"},
  {sentence:"The two companies formed a _____ to share the costs and risks of developing the new technology.",options:["joint venture","public domain","third rail","prix fixe","red guard"],answer:"joint venture"},
  {sentence:"After completing his apprenticeship, the young carpenter became a _____ and worked for a master craftsman.",options:["journeyman","antiquarian","cognoscente","poetaster","huckster"],answer:"journeyman"},
  {sentence:"The mourners recited the _____ at the graveside service, a prayer honoring the memory of the deceased.",options:["kaddish","novena","psalter","shabbat","shekhinah"],answer:"kaddish"},
  {sentence:"The pilot dove his plane in a _____ attack, sacrificing himself to sink the enemy warship.",options:["kamikaze","fabian","expeditionary","monastic","pneumatic"],answer:"kamikaze"},
  {sentence:"The _____ is an unstable subatomic particle that was first discovered in cosmic ray experiments.",options:["kaon","dynamo","sensor","adipocyte","nucleophile"],answer:"kaon"},
  {sentence:"The renowned _____ conducted the court orchestra for the duke, leading performances of symphonies and operas.",options:["kapellmeister","journeyman","thespian","poetaster","huckster"],answer:"kapellmeister"},
  {sentence:"He wrapped a traditional _____ around his head to shield himself from the desert sun.",options:["keffiyeh","wimple","astrakhan","maillot","pith helmet"],answer:"keffiyeh"},
  {sentence:"In Old Norse poetry, a _____ is a figurative phrase like 'whale-road' used in place of 'sea.'",options:["kenning","palindrome","pangram","tmesis","ellipsis"],answer:"kenning"},
  {sentence:"The _____ on the kibbutz worked the fields alongside the other members, sharing everything equally.",options:["kibbutznik","journeyman","antiquarian","cognoscente","huckster"],answer:"kibbutznik"},
  {sentence:"The writer of the opera's text, known as the _____, worked closely with the composer to craft each scene.",options:["librettist","kapellmeister","thespian","poetaster","cognoscente"],answer:"librettist"},
  {sentence:"The dentist injected _____ into the gum tissue to numb the area before starting the procedure.",options:["lidocaine","hydrazine","glycogen","caoutchouc","gentian violet"],answer:"lidocaine"},
  {sentence:"The _____ petals of the daisy were narrow and strap-shaped, radiating outward from the center.",options:["ligulate","obovate","nodose","palpitant","serpiginous"],answer:"ligulate"},
  {sentence:"The _____ nerve plays a crucial role in the sense of taste in the front part of the tongue.",options:["lingual","pulmonic","stomachic","sacroiliac","spondaic"],answer:"lingual"},
  {sentence:"The earthquake triggered _____ of the soil beneath the building, causing it to sink unevenly.",options:["liquefaction","deforestation","acculturation","rejuvenescence","psychogenesis"],answer:"liquefaction"},
  {sentence:"The stock's high _____ meant it could be easily bought and sold without significantly affecting its price.",options:["liquidity","diversity","exclusivity","domesticity","admissibility"],answer:"liquidity"},
  {sentence:"The ancient scribe copied the manuscript _____, reproducing every letter exactly as it appeared in the original.",options:["literatim","impromptu","subito","inter se","ostensibly"],answer:"literatim"},
  {sentence:"The _____ calendar determines the readings and prayers to be used during each church service throughout the year.",options:["liturgical","evangelical","monastic","ecclesiastic","sepulchral"],answer:"liturgical"},
  {sentence:"The farmer kept a small herd of _____ for their soft wool and as pack animals in the Andes.",options:["llama","wombat","saiga","sturgeon","caribou"],answer:"llama"},
  {sentence:"The old sailor was called a _____ by his crew for his stubborn refusal to change course.",options:["loggerhead","huckster","gadfly","poetaster","futilitarian"],answer:"loggerhead"},
  {sentence:"The scholar would _____ late into the night, studying ancient texts by the light of a single lamp.",options:["lucubrate","gormandize","genuflect","procrastinate","economize"],answer:"lucubrate"},
  {sentence:"The oncologist diagnosed the patient with _____, a cancer that originated in the lymph nodes.",options:["lymphoma","carcinoma","mycetoma","splenomegaly","microcephaly"],answer:"lymphoma"},
  {sentence:"The laboratory was equipped to _____ biological samples, freeze-drying them for long-term preservation.",options:["lyophilize","dehumidify","decentralize","democratize","recalculate"],answer:"lyophilize"},
  {sentence:"The experienced _____ operated the CNC machine with precision, producing parts to exact specifications.",options:["machinist","journeyman","huckster","poetaster","thespian"],answer:"machinist"},
  {sentence:"Geologists used a _____ to detect subtle variations in the Earth's magnetic field at the survey site.",options:["magnetometer","hygrometer","defibrillator","micropipette","clepsydra"],answer:"magnetometer"},
  {sentence:"She wore a sleek black _____ for the swimming competition, designed to reduce drag in the water.",options:["maillot","wimple","redingote","astrakhan","keffiyeh"],answer:"maillot"},
  {sentence:"The astrologer warned that a _____ planet was in the ascendant, foretelling misfortune and strife.",options:["malefic","propitious","effulgent","apollonian","monastic"],answer:"malefic"},
  {sentence:"The research _____ outlined each step of the experiment, from data collection through statistical analysis.",options:["methodology","prospectus","panorama","recapitulation","pronouncement"],answer:"methodology"},
  {sentence:"A toxic _____ hung over the swamp, and locals believed breathing it would cause sickness.",options:["miasma","harmattan","vaporescence","exosphere","playa"],answer:"miasma"},
  {sentence:"The infant was born with _____, a condition resulting in an abnormally small head and impaired brain development.",options:["microcephaly","splenomegaly","paraplegia","psychosis","paresthesia"],answer:"microcephaly"},
  {sentence:"The lab technician used a _____ to transfer precisely 5 microliters of reagent into the test tube.",options:["micropipette","magnetometer","hygrometer","defibrillator","clepsydra"],answer:"micropipette"},
  {sentence:"The government's decision to _____ the police force was controversial, arming officers with military-grade equipment.",options:["militarize","democratize","decentralize","economize","unionize"],answer:"militarize"},
  {sentence:"The forest floor was crawling with _____, each one slowly making its way through the leaf litter on hundreds of tiny legs.",options:["millipede","whelk","sturgeon","wombat","saiga"],answer:"millipede"},
  {sentence:"The dictator's _____ gaze made it clear that disobedience would not be tolerated.",options:["minacious","propitious","saccharine","rumbustious","effulgent"],answer:"minacious"},
  {sentence:"The goal of _____ in manufacturing is to reduce waste while maintaining quality.",options:["minimization","reconstruction","recapitulation","validation","recruitment"],answer:"minimization"},
  {sentence:"The old _____ lived alone in a cabin in the woods, despising all human company and modern society.",options:["misanthropic","propitious","impressionable","uninhibited","rumbustious"],answer:"misanthropic"},
  {sentence:"The judge reduced the charge from a felony to a misdemeanor, so the accused became a _____.",options:["misdemeanant","recidivist","futilitarian","paranoiac","loggerhead"],answer:"misdemeanant"},
  {sentence:"Years of _____ left the company deeply in debt, with resources wasted on failed projects.",options:["mismanagement","collegiality","domesticity","admissibility","importunity"],answer:"mismanagement"},
  {sentence:"The new medication helped _____ the patient's chronic pain, making daily activities much easier.",options:["mitigate","exacerbate","commandeer","militarize","procrastinate"],answer:"mitigate"},
  {sentence:"The _____ life of prayer, silence, and manual labor appealed to those seeking spiritual peace.",options:["monastic","rumbustious","dystopian","saccharine","impressionable"],answer:"monastic"},
  {sentence:"The satellite's _____ design meant the outer skin served as both the structure and the protective shell.",options:["monocoque","pneumatic","parabolic","extensible","separable"],answer:"monocoque"}
];
