// UIL Word Power 2025-2026 - Complete Word List
// Format: [word, alternateSpellings (null if none), isVocab (true if marked for vocabulary study)]
const WORD_LIST = [
["a gogo","ago-go",false],
["a posteriori",null,false],
["abapical",null,true],
["abbatial",null,true],
["aberrated",null,false],
["aboveboard",null,false],
["abscess",null,false],
["absolutism",null,false],
["abstruse",null,false],
["academician",null,false],
["acaulescent",null,true],
["acclamation",null,false],
["acculturation",null,true],
["acequia",null,false],
["Achates",null,false],
["Achilles' heel",null,false],
["acoustooptics",null,false],
["acquittance",null,true],
["acumen",null,true],
["ad feminam",null,false],
["adipocyte",null,false],
["admissibility",null,false],
["adroit",null,false],
["advection",null,false],
["adversarial",null,false],
["aegis","egis",false],
["aeroballistics",null,false],
["Aeschylus",null,false],
["afforestation",null,true],
["Agincourt",null,true],
["agnosia",null,false],
["agouti",null,false],
["agrochemical",null,false],
["agronomic",null,false],
["aide-de-camp",null,false],
["aitchbone",null,false],
["akaryocyte",null,false],
["Alamogordo",null,true],
["algorism",null,true],
["alienation",null,false],
["allantoid",null,false],
["allurement",null,false],
["alpha-fetoprotein",null,false],
["altercation",null,true],
["altocumulus",null,true],
["alveolar",null,false],
["amalgamate",null,true],
["ambit",null,false],
["amnesiac",null,false],
["amortization",null,false],
["amphorae",null,true],
["amrita","amreeta",false],
["anacoluthon",null,true],
["analgesic",null,true],
["anamnesis",null,true],
["anaplastic",null,false],
["anarthrous",null,false],
["anchoress",null,false],
["anemometer",null,false],
["anion",null,false],
["annotation",null,false],
["annunciation","Annunciation",false],
["anodyne",null,false],
["anoxia",null,false],
["antemortem",null,false],
["anteroom",null,false],
["anticoagulant",null,true],
["antipersonnel",null,true],
["antiquarian",null,false],
["antithesis",null,true],
["Anzio",null,false],
["apatetic",null,true],
["aperture",null,false],
["apocalyptic",null,true],
["Apollonian","apollonian",false],
["apostate",null,false],
["apprise",null,false],
["aqueous",null,false],
["aquifer",null,true],
["arborescent",null,false],
["Archimedean screw",null,false],
["argentiferous",null,false],
["arioso",null,false],
["aromaticity",null,false],
["arraignment",null,false],
["arriere-pensee",null,false],
["art nouveau","Art Nouveau",false],
["asparagus","Asparagus",false],
["asperse",null,false],
["aspirant",null,false],
["assuage",null,true],
["assurgency",null,false],
["astrakhan","astrachan",false],
["atemoya",null,false],
["atrabilious",null,false],
["Atticism","atticism",false],
["attribution",null,false],
["au pair",null,false],
["augur",null,false],
["auriferous",null,true],
["autologous",null,false],
["averse",null,false],
["avian",null,false],
["avirulent",null,false],
["avuncular",null,false],
["bacteremia",null,false],
["Bactrian camel",null,false],
["bagasse",null,true],
["bagatelle",null,false],
["Bakelite",null,false],
["balaclava",null,false],
["baleen whale",null,false],
["balneal",null,false],
["bangkok","Bangkok",false],
["bar mitzvah","bar mizvah",false],
["barnburner",null,false],
["baroque","Baroque",false],
["Baryshnikov",null,false],
["Bataan",null,true],
["bathypelagic",null,true],
["Bauhaus",null,true],
["beaus","beaux",false],
["Bedouin","Beduin",false],
["Begin",null,false],
["Bellerophon",null,true],
["benignancy",null,true],
["benison",null,false],
["bergamot",null,true],
["Bessarabia",null,false],
["bibliotheca",null,false],
["bight",null,false],
["bimestrial",null,false],
["biometeorology",null,false],
["bioresearch",null,false],
["biostatistics",null,true],
["blastula",null,false],
["board-certified",null,false],
["bodhisattva",null,false],
["booboisie",null,true],
["bouleversement",null,true],
["Brailler","brailler",false],
["bratwurst",null,false],
["breviaries",null,true],
["brio",null,true],
["Briticism",null,false],
["brocatelle",null,false],
["brotherliness",null,false],
["brusquerie",null,true],
["Buddha",null,false],
["burdensome",null,false],
["Burundi",null,false],
["cabaret",null,false],
["cabochon",null,false],
["cacophonous",null,true],
["calibrator",null,true],
["calumnious",null,false],
["Canaanite",null,true],
["cangue",null,false],
["cantonment",null,false],
["caoutchouc",null,false],
["caparison",null,false],
["capitulation",null,false],
["capuchin","Capuchin",false],
["carabiner","karabiner",false],
["cardiovascular",null,false],
["carnelian",null,false],
["carrefour",null,false],
["caseous",null,true],
["Cassiopeia",null,false],
["cataclysmal",null,false],
["Catch-22","catch-22",false],
["cathect",null,true],
["caudate",null,false],
["cauterization",null,true],
["caveat emptor",null,false],
["cede",null,true],
["cellulitis",null,false],
["centaur",null,false],
["cephalic",null,true],
["cerebrate",null,false],
["cernuous",null,false],
["chagrin",null,true],
["chambered nautilus",null,false],
["chamomile","camomile",false],
["chancellor",null,false],
["channelize",null,false],
["charge d'affaires",null,false],
["chassepot",null,false],
["chastise",null,false],
["chef-d'oeuvre",null,false],
["chemurgy",null,false],
["chervil",null,false],
["Chiang Kai-shek",null,false],
["chicanery",null,false],
["chiliad",null,false],
["chi-square",null,false],
["chloasma",null,false],
["chorizo",null,false],
["chronicled",null,true],
["chutzpah","hutzpah",false],
["Cinco de Mayo",null,false],
["cingulate",null,false],
["circumflex",null,false],
["circumspect",null,true],
["cismontane",null,true],
["Cistercian",null,true],
["Clausewitz",null,false],
["clepsydra",null,false],
["coadunate",null,true],
["coccyx",null,true],
["cochlea",null,false],
["coequal",null,false],
["cogitative",null,false],
["cognoscente",null,false],
["collegiality",null,true],
["colloquium",null,false],
["color-code",null,false],
["comelier",null,false],
["commandeer",null,false],
["commination",null,false],
["communicative",null,true],
["compeer",null,false],
["compensatory",null,false],
["complacent",null,false],
["comprador","compradores",false],
["conceptualize",null,false],
["concomitant",null,false],
["concrescence",null,true],
["concussion",null,false],
["condolatory",null,true],
["condyle",null,true],
["confabulation",null,false],
["consentaneous",null,false],
["consomme",null,false],
["conspicuous",null,false],
["constrictor",null,false],
["consulate",null,false],
["consumerism",null,false],
["continuity",null,false],
["contrapposto",null,false],
["contumacious",null,false],
["convalescence",null,false],
["copacetic","copasetic",false],
["cormorant",null,false],
["corporeity",null,false],
["corpsman",null,false],
["corroborating",null,false],
["cosmology",null,false],
["Cote d'Ivoire",null,false],
["counterfactual",null,true],
["coup de grace",null,false],
["crampons",null,true],
["creativity",null,false],
["credible",null,false],
["Creutzfeldt-Jakob disease",null,false],
["crewel",null,true],
["cronyism",null,true],
["crotchety",null,false],
["cruet",null,true],
["cryosurgery",null,true],
["cummerbund",null,true],
["curmudgeon",null,false],
["curtate",null,false],
["cutlery",null,false],
["cycloid",null,false],
["Cyrillic",null,false],
["daedal",null,false],
["daiquiri",null,false],
["daltonism","Daltonism",false],
["Damascus",null,true],
["darnel",null,false],
["dasyurid",null,false],
["de rigueur",null,false],
["dealate",null,false],
["debauched",null,false],
["debriefing",null,false],
["decalcomania",null,false],
["decentralize",null,false],
["decoupage","decoupage",false],
["decrypt",null,false],
["de-escalate","deescalate",false],
["deference",null,false],
["defibrillator",null,false],
["deforestation",null,false],
["degauss",null,false],
["dehumidify",null,false],
["delimiter",null,false],
["della Robbia",null,false],
["demagoguery",null,false],
["democratize",null,false],
["demolitionist",null,false],
["demonstrable",null,false],
["dendritic",null,false],
["denigrate",null,false],
["denuclearize",null,false],
["depletion",null,false],
["deploy",null,true],
["depreciation",null,false],
["derivation",null,false],
["derringer",null,false],
["Descartes",null,true],
["desiccate",null,true],
["desipramine",null,false],
["destabilization",null,false],
["deuteranopia",null,true],
["devil's advocate",null,false],
["devolatilize",null,false],
["dhobi",null,false],
["diachronic",null,false],
["diaphanous",null,false],
["diatomaceous",null,true],
["diatribe",null,false],
["dictum",null,false],
["dietetics",null,false],
["diffusion",null,false],
["dilatation",null,false],
["dinosaurian",null,false],
["Diogenes",null,false],
["disabuse",null,false],
["disbursal",null,true],
["discomfited",null,true],
["discretion",null,false],
["disengagement",null,false],
["disinterred",null,false],
["dispensary",null,false],
["disproportional",null,false],
["disseminate",null,true],
["dissuade",null,false],
["distillate",null,false],
["diva",null,false],
["diversity",null,false],
["divination",null,false],
["do-it-yourselfer",null,false],
["domesticity",null,false],
["Dostoyevsky","Dostoevski",false],
["doublethink",null,false],
["drogue",null,false],
["dubiety",null,true],
["dulcimer",null,true],
["duty-free",null,false],
["duumvirate",null,false],
["dynamo",null,true],
["dyspepsia",null,false],
["dystopian",null,true],
["ecclesiasticism",null,false],
["echeveria","Echeveria",false],
["echolocation",null,true],
["economize",null,false],
["Ecuador",null,true],
["eeriest",null,false],
["efficacious",null,true],
["effulgent",null,false],
["eiderdown","eider down",false],
["electability",null,false],
["elegize",null,false],
["elevenses",null,false],
["ellipsis",null,false],
["emaciation",null,true],
["emendate",null,true],
["emigrate",null,false],
["emigre",null,false],
["eminent domain",null,true],
["empanada",null,false],
["empressement",null,false],
["en brochette",null,true],
["encaustic",null,false],
["encroachment",null,false],
["encyclical",null,false],
["enigmatical",null,true],
["enrapture",null,false],
["entanglement",null,false],
["entrechat",null,true],
["entree","entree",false],
["entry-level",null,false],
["enzymology",null,false],
["epeirogeny",null,true],
["epicycle",null,false],
["epidermis",null,false],
["epigraph",null,false],
["epiphany","Epiphany",false],
["episcopacy",null,false],
["epistemologist",null,false],
["epistle","Epistle",false],
["equerry",null,true],
["equilibrate",null,false],
["equivoque","equivoke",false],
["Erlenmeyer flask",null,false],
["erysipeloid",null,false],
["escarole",null,true],
["escarpment",null,true],
["esophagus","oesophagus",false],
["esprit de corps",null,false],
["etesian",null,false],
["ethereal",null,true],
["ethnomusicology",null,false],
["etymon",null,false],
["eucalyptus","Eucalyptus",false],
["euphoric",null,false],
["Eurocentric",null,false],
["euryphagous",null,false],
["euxinic",null,false],
["evangelical","Evangelical",false],
["evection",null,false],
["eventuality",null,false],
["exacerbate",null,false],
["Excalibur",null,true],
["exceptive",null,false],
["exclusivity",null,false],
["executrix",null,false],
["exemplum",null,true],
["exhortative",null,false],
["exiguity",null,false],
["exodontics",null,true],
["exosphere",null,false],
["expansionism",null,false],
["expeditionary",null,true],
["expose",null,false],
["expostulatory",null,false],
["expurgate",null,false],
["extensible",null,false],
["extortioner",null,false],
["extraordinaire",null,false],
["extricate",null,false],
["Fabian",null,false],
["fair market value",null,false],
["falcate",null,true],
["fanfaronade",null,false],
["farandole",null,true],
["fascinator",null,false],
["Fascisti",null,true],
["fastigium",null,false],
["faun",null,true],
["featherstitch",null,false],
["feigned",null,false],
["felicitation",null,false],
["feminism",null,false],
["ferocity",null,false],
["Ferris wheel","ferris wheel",false],
["festinate",null,false],
["festschrift",null,true],
["fiducial",null,true],
["filet mignon",null,false],
["fillip",null,false],
["filoplume",null,false],
["firebrand",null,false],
["fissipalmate",null,true],
["flagitious",null,true],
["fleche",null,false],
["flextime",null,false],
["floruit",null,false],
["flotation device",null,false],
["fluorescence",null,false],
["fluviomarine",null,false],
["fluxion",null,false],
["folie a deux",null,false],
["foramina",null,true],
["foreground",null,false],
["fortitudinous",null,true],
["Franciscan",null,true],
["Frankenstein",null,false],
["fremitus",null,true],
["frivolity",null,false],
["fructify",null,false],
["funereal",null,false],
["fungicidal",null,false],
["futilitarian",null,false],
["gadfly",null,true],
["gamosepalous",null,false],
["garbanzo",null,false],
["garden-variety",null,false],
["gavel-to-gavel",null,false],
["Gelandesprung",null,false],
["genealogist",null,true],
["genome",null,false],
["gentian violet",null,true],
["genuflect",null,false],
["geophagy",null,false],
["Gettysburg",null,false],
["gigot",null,false],
["gimlet-eyed",null,false],
["gimmal",null,true],
["gingerroot",null,false],
["gladiolus","Gladiolus",false],
["glitterati",null,false],
["glycogen",null,false],
["Gordian knot",null,false],
["gormandize",null,true],
["Gouda",null,false],
["granulocyte",null,false],
["gravitas",null,true],
["Grecism",null,false],
["grenadier",null,true],
["grievousness",null,false],
["grotto",null,false],
["guardant","gardant",false],
["gudgeon",null,false],
["guillemot",null,true],
["gurney",null,false],
["gymnosophist",null,false],
["habanera",null,false],
["Haggadah","Haggada",false],
["halcyon","Halcyon",false],
["Hanoi",null,false],
["hapax legomenon",null,false],
["harmattan",null,true],
["Havasupai",null,false],
["haversack",null,false],
["Hebraic",null,true],
["hedge fund",null,false],
["Hegelianism",null,true],
["helical",null,false],
["heliometer",null,false],
["hemodialysis",null,false],
["hepatotoxicity",null,false],
["heptathlon",null,false],
["herbalist",null,false],
["heroic verse",null,true],
["herpetologist",null,false],
["heterodox",null,false],
["heterogenous",null,false],
["Hibernia",null,true],
["high-def",null,false],
["Himalaya Mountains",null,false],
["Hippocrene",null,false],
["histology",null,false],
["histrionic",null,true],
["hoisin sauce",null,false],
["honorific",null,true],
["hors d'oeuvre",null,false],
["howdah","houdah",false],
["huckster",null,false],
["humiliation",null,false],
["hydrazine",null,false],
["hydrogeology",null,false],
["hygienics",null,false],
["hygrometer",null,true],
["hylozoism",null,false],
["hypabyssal",null,false],
["hypnophobia",null,true],
["hypothetical",null,false],
["iatrogenic",null,false],
["ichthyic",null,false],
["iconography",null,false],
["idee fixe",null,false],
["illative",null,false],
["ill-fated",null,false],
["Illyrian",null,false],
["imbecility",null,false],
["immanent",null,true],
["immemorial",null,false],
["immunocompetent",null,false],
["impasse",null,true],
["imperceptive",null,false],
["imperialism",null,true],
["importunity",null,false],
["impracticable",null,false],
["impressionable",null,false],
["impressionism","Impressionism",false],
["impromptu",null,true],
["imprudence",null,false],
["imputable",null,false],
["in absentia",null,true],
["in vivo",null,false],
["inadmissible",null,false],
["inchoate",null,false],
["incidentally",null,true],
["incommodious",null,true],
["incontrovertible",null,false],
["inculcate",null,false],
["indecisiveness",null,false],
["indeterminable",null,false],
["indistinguishable",null,false],
["individuation",null,false],
["indurate",null,false],
["ineptitude",null,false],
["infallibility",null,false],
["infinitesimal",null,true],
["inflatable",null,false],
["ingesta",null,true],
["inoculation",null,true],
["inquisition","Inquisition",false],
["insidious",null,true],
["insoluble",null,false],
["instant replay",null,false],
["instantaneous",null,false],
["instauration",null,true],
["insurmountable",null,false],
["inter se",null,true],
["intercede",null,false],
["intergenerational",null,false],
["interleukin-1",null,false],
["interscholastic",null,false],
["interstellar",null,false],
["intravasation",null,false],
["intuitionism",null,false],
["intumesce",null,false],
["inukshuk",null,false],
["iridescence",null,false],
["irrecusable",null,false],
["irremediable",null,false],
["Islamabad",null,false],
["isolable",null,false],
["Israeli",null,false],
["Jacobinical",null,false],
["Jacuzzi",null,false],
["janissary",null,true],
["Jarlsberg",null,true],
["Javanese",null,false],
["Jekyll and Hyde",null,false],
["jet lag","jetlag",false],
["jeunesse doree",null,false],
["jobbery",null,false],
["joint venture",null,false],
["journeyman",null,false],
["Judea","Judaea",false],
["judicable",null,false],
["Jungian",null,false],
["junketeer",null,false],
["juvenility",null,false],
["Kaddish",null,true],
["kamikaze",null,false],
["kaon",null,false],
["Kapellmeister",null,false],
["Karbala",null,false],
["keffiyeh","kaffiyeh",true],
["kegler",null,false],
["kenning",null,false],
["Ketchikan",null,true],
["Keynesian",null,false],
["khapra beetle",null,false],
["kibbutznik",null,false],
["kinesthesia",null,true],
["kineticism",null,false],
["Klein bottle",null,false],
["klutzy",null,false],
["knockdown-dragout",null,false],
["Komodo dragon",null,false],
["kraken",null,true],
["Kurdish",null,false],
["kurtosis",null,false],
["Kyrgyzstan",null,false],
["Labrador retriever",null,false],
["labret",null,false],
["laetrile",null,false],
["laity",null,true],
["lambdoid",null,false],
["laminectomy",null,false],
["lamprophyre",null,false],
["langlauf",null,true],
["languidly",null,false],
["languor",null,false],
["lanuginous",null,false],
["lapidarian",null,true],
["last hurrah",null,false],
["Latinism",null,false],
["laureate",null,true],
["leachate",null,true],
["lebensraum",null,false],
["legatine",null,false],
["legitimize",null,false],
["Leninism",null,false],
["lentissimo",null,false],
["leptocephalus",null,false],
["lese majesty","lese majeste",false],
["leukoderma","leucoderma",false],
["lexicography",null,true],
["libelous","libellous",false],
["librarian",null,false],
["librettist",null,true],
["lidocaine",null,false],
["ligulate",null,false],
["limacine",null,false],
["lingual",null,false],
["liquefaction",null,false],
["liquidity",null,false],
["literatim",null,false],
["litigate",null,false],
["liturgical",null,false],
["llama",null,false],
["loggerhead",null,false],
["longanimity",null,false],
["lotus position",null,true],
["Louis Quatorze",null,false],
["lucubrate",null,false],
["luminosity",null,false],
["Lupercalia",null,true],
["lycanthropy",null,true],
["lymphoma",null,false],
["lyophilize",null,true],
["lyrebird",null,false],
["macabre",null,true],
["maceration",null,false],
["machinist",null,false],
["macroeconomics",null,true],
["Maghreb","Maghrib",false],
["magnetometer",null,false],
["Maharashtra",null,false],
["maillot",null,false],
["maitre d'hotel",null,false],
["majoritarianism",null,false],
["mal de mer",null,true],
["Malawi",null,false],
["malefic",null,false],
["malodor",null,true],
["Malthusian",null,true],
["Mandaean","Mandean",false],
["mandala",null,true],
["mandrill",null,true],
["manganese",null,false],
["manicotti",null,true],
["manorial",null,true],
["Maori",null,false],
["marcescent",null,true],
["marjoram",null,false],
["marmalade",null,false],
["marquisette",null,false],
["mascarpone",null,true],
["masculinity",null,false],
["materfamilias",null,false],
["materiel","materiel",false],
["maxillary",null,false],
["mayoralty",null,false],
["Mbundu",null,false],
["McIntosh",null,false],
["mechanoreceptor",null,false],
["medicable",null,false],
["Medicaid","medicaid",false],
["megalomania",null,true],
["melatonin",null,false],
["Melbourne",null,false],
["melliferous",null,false],
["melodramatic",null,false],
["menhir",null,true],
["men-of-war",null,false],
["mephitis",null,false],
["mercury vapor lamp",null,false],
["merganser",null,false],
["merriment",null,false],
["mesophyte",null,false],
["messianism",null,false],
["metabolically",null,true],
["metaphrast",null,false],
["metastasize",null,false],
["meteoroid",null,false],
["methodology",null,true],
["metrication",null,false],
["miasma",null,true],
["microampere",null,false],
["microcephaly",null,false],
["micropipette",null,true],
["Midas touch",null,false],
["Midrash",null,true],
["militarize",null,false],
["miller's thumb",null,false],
["millipede","millepede",false],
["minacious",null,false],
["miniature schnauzer",null,false],
["minimization",null,false],
["Minotaur",null,false],
["minute of arc",null,false],
["misally",null,false],
["misanthropic",null,false],
["misdemeanant",null,false],
["mismanagement",null,false],
["misology",null,true],
["missa cantata",null,false],
["mitigate",null,true],
["mobocratic",null,true],
["modularized",null,false],
["Molokai","Moloka'i",false],
["monastic",null,false],
["Monet",null,false],
["mongrelize",null,false],
["monochasium",null,true],
["monocoque",null,true],
["mononucleosis",null,false],
["monopod",null,false],
["monteith",null,true],
["moraine",null,false],
["morality",null,true],
["morphosis",null,false],
["mortarboard",null,false],
["mosaic","Mosaic",false],
["motile",null,true],
["moussaka",null,false],
["mucilage",null,false],
["mukluks",null,true],
["mullah","mulla",false],
["mulligatawny",null,true],
["multilateral",null,true],
["multivoltine",null,false],
["mummichog",null,false],
["musculature",null,false],
["muster roll",null,true],
["mutinous",null,false],
["muttonchops",null,false],
["mycetoma",null,true],
["myiasis",null,false],
["myosotis","Myosotis",false],
["myrrh",null,false],
["mythomania",null,true],
["Nablus",null,false],
["nabob",null,true],
["Namibia",null,true],
["narrow-minded",null,false],
["Naugahyde",null,false],
["Nazification",null,false],
["nefariously",null,true],
["negativism",null,false],
["nematocide","nematicide",false],
["nephrogenous",null,false],
["netiquette",null,false],
["neuromuscular",null,false],
["New Left",null,false],
["newsmagazine",null,false],
["nidicolous",null,true],
["Nietzsche",null,true],
["nightmarishly",null,false],
["nine days' wonder",null,false],
["nitrogen narcosis",null,false],
["nodose",null,false],
["no-fault",null,false],
["non prosequitur",null,false],
["nonagenarian",null,true],
["nonchalant",null,false],
["noncompliance",null,false],
["nonexistent",null,false],
["noninvasive",null,false],
["noradrenergic",null,false],
["noteworthiness",null,false],
["novena",null,false],
["nucleophile",null,true],
["nuncupative",null,false],
["oarlock",null,false],
["obfuscation",null,false],
["objectivism","Objectivism",false],
["obliquity",null,true],
["obovate",null,false],
["obscenity",null,false],
["obsolescence",null,false],
["occidentalize","Occidentalize",false],
["octogenarian",null,false],
["odalisque","odalisk",false],
["oedipal","Oedipal",false],
["offensiveness",null,false],
["offshore",null,false],
["O'Keeffe",null,false],
["olecranon",null,true],
["oleic acid",null,false],
["oligopsony",null,true],
["olla podrida",null,false],
["omnipotent","Omnipotent",false],
["oncornavirus",null,false],
["opera bouffe",null,true],
["opine",null,false],
["oppositionist",null,false],
["Oranjestad",null,false],
["Ordovician",null,false],
["organically",null,false],
["organoleptic",null,true],
["originalism",null,false],
["ornithosis",null,false],
["orthoscopic",null,true],
["Osceola",null,false],
["osprey",null,false],
["ossature",null,false],
["ostensibly",null,false],
["osteopathy",null,true],
["otalgia",null,false],
["Ouija",null,false],
["outre",null,true],
["outsourcing",null,false],
["overdog",null,false],
["overemphasize",null,false],
["oxycephaly",null,false],
["pablum","Pablum",false],
["pack rat",null,false],
["Paganini",null,false],
["paisano",null,true],
["Palau",null,false],
["palaver",null,false],
["Paleolithic",null,false],
["paleozoology",null,false],
["palindrome",null,true],
["palmary",null,false],
["palpitant",null,false],
["paludal",null,true],
["panacean",null,true],
["pancreatectomy",null,false],
["Panglossian",null,true],
["pangram",null,false],
["panorama",null,false],
["papacy","Papacy",false],
["parabolic",null,false],
["parameter",null,false],
["paranoiac",null,false],
["parapet",null,false],
["paraplegia",null,false],
["parataxis",null,true],
["paresthesia","paraesthesia",false],
["parfleche",null,false],
["parishioner",null,false],
["Parnassian",null,true],
["parolee",null,false],
["paronomasia",null,false],
["parterre",null,false],
["parvovirus",null,false],
["pas de deux",null,false],
["pasqueflower",null,true],
["passe-partout",null,false],
["pasteurization",null,false],
["pastina",null,false],
["patency",null,true],
["patriarchy",null,false],
["patulous",null,false],
["Pavlovian",null,true],
["peccant",null,true],
["pedantic",null,false],
["pediatrician",null,false],
["peignoir",null,false],
["pellucid",null,true],
["penetralia",null,false],
["penuche","penuchi",false],
["penultimate",null,false],
["perambulate",null,false],
["perdition",null,false],
["peregrinator",null,false],
["perinephrium",null,false],
["peripatetic","Peripatetic",false],
["periphrasis",null,false],
["perishable",null,false],
["permissibility",null,false],
["peroral",null,false],
["persnickety",null,true],
["pervade",null,false],
["pestilential",null,true],
["Petrarchan sonnet",null,false],
["phantasmagoria",null,true],
["pharaoh hound",null,false],
["phenomenalism",null,false],
["philosophize",null,true],
["Phoenician",null,false],
["phreatic",null,false],
["phylogeny",null,false],
["phytophagous",null,false],
["piccolo",null,false],
["pierogi",null,false],
["Pillars of Hercules",null,false],
["piosity",null,false],
["pisciculture",null,true],
["pith helmet",null,false],
["plaintiff",null,false],
["plasmapheresis",null,false],
["plaudit",null,false],
["playa",null,false],
["plenary",null,false],
["pleuropneumonia",null,false],
["pleuston",null,true],
["plosive",null,false],
["plunger",null,false],
["pneumatic",null,false],
["poet laureate",null,true],
["poetaster",null,true],
["poinciana",null,false],
["poison-pen letter",null,false],
["polarize",null,false],
["politesse",null,false],
["polliniferous","polleniferous",false],
["poltroon",null,true],
["polynya",null,true],
["pomace",null,false],
["pomiculture",null,false],
["pomology",null,true],
["pontonier",null,false],
["Ponzi scheme",null,true],
["populism","Populism",false],
["porcelain",null,false],
["portamento",null,true],
["portiere",null,true],
["Portuguese man-of-war",null,false],
["postbellum",null,false],
["poste restante",null,false],
["posthumous",null,false],
["postiche",null,true],
["postulant",null,false],
["potable",null,true],
["praedial","predial",false],
["praenomen",null,true],
["praying mantis",null,false],
["preachment",null,false],
["predecease",null,false],
["predestinarian",null,false],
["predominately",null,false],
["prefatory",null,true],
["prelapsarian",null,true],
["prelude",null,false],
["prequel",null,false],
["presbyterian","Presbyterian",false],
["preteenager",null,false],
["prima donna",null,true],
["primavera",null,false],
["primitivism",null,false],
["principium",null,true],
["prix fixe",null,false],
["procephalic",null,false],
["proclivities",null,false],
["procrastinate",null,false],
["progenitor",null,false],
["prolepsis",null,false],
["pronouncement",null,false],
["prophesier",null,true],
["propitious",null,true],
["proscription",null,false],
["prosecutorial",null,true],
["prosopography",null,false],
["prospectus",null,false],
["protanopia",null,true],
["protestation",null,false],
["proventriculus",null,false],
["Psalter","psalter",false],
["pseudonymous",null,false],
["psychogenesis",null,true],
["psychosis",null,false],
["ptyalism",null,false],
["public domain",null,false],
["pulmonic",null,false],
["punctilio",null,true],
["Puritanism","puritanism",false],
["pusillanimous",null,false],
["Pyongyang",null,false],
["pyriform",null,false],
["pythonic",null,false],
["Qattara Depression",null,false],
["Qu'Appelle River",null,false],
["quadrennium",null,false],
["quadriceps",null,false],
["quadrumvirate",null,true],
["quaestor",null,false],
["qualitative analysis",null,false],
["quartile",null,false],
["quell",null,false],
["quercitron",null,false],
["queued",null,true],
["quiddity",null,false],
["quillwork",null,false],
["quindecennial",null,false],
["Quirinal",null,true],
["quondam",null,true],
["rabble-rouser",null,false],
["Rabelais",null,false],
["radicchio",null,false],
["radiolocation",null,true],
["radon",null,false],
["ragwort",null,false],
["rakehell",null,false],
["Ramadan",null,false],
["rampion",null,false],
["ranula",null,true],
["rapprochement",null,true],
["Rastafarianism",null,false],
["ravening",null,true],
["Rayleigh wave",null,false],
["razzmatazz",null,false],
["reactivate",null,false],
["rear-ended",null,false],
["recalculate",null,false],
["recapitulation",null,false],
["recidivist",null,true],
["recommendation",null,false],
["reconstruction","Reconstruction",false],
["recruitment",null,false],
["recurrent",null,false],
["Red Guard",null,false],
["red herring",null,true],
["redingote",null,false],
["redintegration",null,false],
["reductio ad absurdum",null,false],
["redux",null,false],
["reflexology",null,false],
["refulgent",null,true],
["regardless",null,false],
["regisseur",null,false],
["regressive",null,false],
["reify",null,false],
["reimportation",null,false],
["reincarnate",null,false],
["rejuvenescence",null,false],
["reliquiae",null,true],
["remittent",null,false],
["remuneration",null,false],
["rendition",null,false],
["renewable",null,false],
["repatriate",null,false],
["repentant",null,false],
["repine",null,true],
["replete",null,false],
["representative",null,false],
["reprieve",null,false],
["reprise",null,false],
["reproof",null,false],
["reptilian",null,false],
["requisition",null,false],
["rerelease",null,false],
["rescind",null,false],
["resorption",null,false],
["restitution",null,true],
["restrictionism",null,false],
["reticulate",null,false],
["retinoscopy",null,false],
["retorsion","retortion",false],
["retrocede",null,false],
["reunification",null,false],
["revelation","Revelation",false],
["reverie",null,true],
["revisionary",null,false],
["rhesus monkey",null,true],
["rhinencephalon",null,false],
["Rhodes scholar",null,false],
["rhododendron","Rhododendron",false],
["rhodolite",null,false],
["rhonchus",null,false],
["rhyme royal",null,false],
["ribband",null,false],
["rickettsiosis",null,false],
["rigor mortis",null,false],
["rime riche",null,true],
["rite of passage",null,false],
["ritualistic",null,false],
["robotics",null,false],
["rockabilly",null,false],
["Roethke",null,false],
["Romano",null,false],
["rondelet",null,false],
["rose of Sharon",null,false],
["roster",null,false],
["Rotarian",null,true],
["rotogravure",null,false],
["royalism",null,true],
["rubasse",null,false],
["rubefacient",null,false],
["rubrician",null,false],
["ruinate",null,false],
["rumbustious",null,true],
["rupicolous",null,true],
["ruse",null,false],
["Russophobia",null,false],
["Saarland",null,true],
["saber rattling",null,false],
["saccade",null,false],
["saccharine",null,false],
["sacerdotalism",null,true],
["sackcloth",null,false],
["sacramentalism",null,false],
["sacroiliac",null,false],
["sage grouse",null,false],
["saiga","Saiga",false],
["saint's day",null,false],
["salad days",null,false],
["salience",null,true],
["sally lunn",null,true],
["Saltillo",null,true],
["Salzburg",null,false],
["Samoan",null,false],
["San Andreas Fault",null,false],
["sanctum sanctorum",null,false],
["Sanforized",null,false],
["Santa Gertrudis",null,false],
["Sarajevo",null,false],
["sarcoptic mange",null,false],
["satori",null,false],
["saurian",null,false],
["saute",null,false],
["saxophone",null,false],
["scabbard",null,false],
["scampi",null,false],
["scansorial",null,true],
["scapular",null,false],
["scenarist",null,false],
["scherzando",null,false],
["schmatte",null,false],
["scholasticism","Scholasticism",false],
["sciaenid",null,false],
["scintilla",null,false],
["scire facias",null,false],
["scissile",null,false],
["sclerous",null,false],
["scotoma",null,false],
["scoundrelly",null,false],
["screed",null,false],
["screenprint",null,false],
["scriptwriter",null,false],
["scrobiculate",null,false],
["scullery",null,false],
["scurrility",null,false],
["seagirt",null,false],
["second-guess",null,false],
["sedate",null,true],
["selaginella","Selaginella",false],
["selenology",null,true],
["self-incrimination",null,false],
["seme",null,false],
["semidivine",null,false],
["sensor",null,false],
["separable",null,false],
["septa",null,false],
["septennial",null,false],
["sepulchral",null,false],
["sericeous",null,true],
["serpiginous",null,false],
["serval",null,true],
["sexcentenary",null,false],
["Shabbat",null,false],
["shaitan","Shaitan",false],
["Shakespeareana",null,false],
["Shakespeariana",null,false],
["shalom",null,false],
["Shangri-la",null,false],
["Shekhinah",null,false],
["Sherpa",null,false],
["shiatsu",null,false],
["shofar",null,true],
["Shriner",null,false],
["siccative",null,true],
["sidereal",null,false],
["sierozem",null,false],
["silage",null,true],
["simian",null,false],
["simulacrum",null,true],
["sinecure",null,true],
["sinistrorse",null,false],
["skittery",null,false],
["slalomed",null,false],
["sluggard",null,true],
["Snellen chart",null,false],
["snickersnee",null,false],
["sobriety",null,false],
["sociability",null,false],
["sockdolager","sockdologer",false],
["Socratic irony",null,false],
["solfatara",null,false],
["solitudinarian",null,false],
["solmization",null,false],
["solubility",null,false],
["somatology",null,true],
["somniferous",null,false],
["songstress",null,false],
["sorghum","Sorghum",false],
["soubrette",null,false],
["soupcon",null,false],
["soutache",null,true],
["spangle",null,true],
["Spanglish",null,false],
["spatula",null,false],
["spavined",null,false],
["speculator",null,false],
["sphagnum","Sphagnum",false],
["spherometer",null,true],
["spinescent",null,false],
["splenomegaly",null,false],
["spondaic",null,false],
["spring peeper",null,false],
["staccato",null,false],
["stagflation",null,false],
["Stanford-Binet test",null,false],
["stardust",null,false],
["stellar",null,false],
["stem christie",null,false],
["stenophagous",null,false],
["steppingstone",null,false],
["sternocleidomastoid",null,true],
["stichometry",null,true],
["stippled",null,false],
["stodgy",null,false],
["stomachic",null,false],
["Stonehenge",null,false],
["Stradivari",null,true],
["stratigraphy",null,false],
["stricture",null,false],
["strontium",null,true],
["struthious",null,false],
["sturgeon",null,false],
["subaudition",null,false],
["subito",null,true],
["subluxation",null,false],
["submergence",null,false],
["subornation",null,true],
["subreption",null,false],
["subtlety",null,false],
["succussion",null,false],
["sudorific",null,false],
["superciliary",null,false],
["supernumerary",null,false],
["supinate",null,false],
["supplicatory",null,false],
["surcingle",null,false],
["susceptibility",null,false],
["swashbuckler",null,true],
["sylvatic",null,true],
["symposiarch",null,false],
["synchronous",null,false],
["syneresis","synaeresis",false],
["synopsize",null,false],
["taboret","tabouret",false],
["tachistoscope",null,true],
["tacit",null,true],
["Taipei",null,false],
["Taiwanese",null,false],
["talisman",null,false],
["tandoor",null,false],
["tantara",null,true],
["tapioca",null,false],
["tarboosh","tarbush",false],
["tarradiddle","taradiddle",true],
["tax-deductible",null,false],
["technological",null,false],
["telecommunication",null,false],
["televangelist",null,false],
["tempera",null,false],
["tendentious","tendencious",false],
["tenebrific",null,true],
["tenuous",null,true],
["Teotihuacan",null,false],
["tergiversate",null,true],
["teriyaki",null,false],
["terraqueous",null,false],
["tete-a-tete",null,false],
["tetrarch",null,false],
["tetrazzini","Tetrazzini",false],
["thaumatology",null,true],
["theocentric",null,false],
["theorist",null,false],
["theriomorphic",null,false],
["thespian","Thespian",false],
["third rail",null,false],
["thoroughbred","Thoroughbred",false],
["thrasonical",null,true],
["thyroidectomy",null,true],
["Tibet",null,false],
["Tigris",null,false],
["tiki","Tiki",false],
["timbre",null,true],
["timetable",null,false],
["Timor",null,false],
["titivate",null,false],
["tmesis",null,false],
["toga virilis",null,false],
["tonka bean",null,false],
["toothsome",null,false],
["Tophet",null,true],
["torturous",null,true],
["tough-minded",null,false],
["toxicity",null,true],
["tranquillity","tranquility",false],
["transhumance",null,true],
["transitionary",null,true],
["transnational",null,false],
["transpicuous",null,false],
["transposition",null,false],
["travelogue","travelog",false],
["triable",null,false],
["triangulate",null,false],
["triceps",null,false],
["trifoliate",null,false],
["trilithon",null,false],
["triskaidekaphobia",null,true],
["tritanopia",null,false],
["troika",null,false],
["tumorigenic",null,false],
["turgescence",null,false],
["twaddle",null,true],
["Tyrrhenian Sea",null,false],
["ultramundane",null,false],
["ultrasonic",null,false],
["Ulysses",null,false],
["una corda",null,false],
["unambiguous",null,false],
["unbidden",null,false],
["uncharacteristic",null,false],
["uncorroborated",null,false],
["uncouth",null,false],
["undermine",null,false],
["underpinning",null,true],
["undersecretary",null,false],
["unfailing",null,false],
["unflappable",null,false],
["unhallowed",null,false],
["unification",null,false],
["unilateralism",null,false],
["unimpeachable",null,false],
["uninhibited",null,false],
["unionize",null,false],
["universal donor",null,false],
["unlettered",null,false],
["unnameable","unnamable",false],
["unremitting",null,false],
["unriddle",null,false],
["unstratified",null,false],
["untoward",null,false],
["unwittingly",null,false],
["unwonted",null,true],
["uraeus",null,false],
["user-friendly",null,false],
["usufruct",null,true],
["Uyghur","Uighur",false],
["vaccinate",null,false],
["vacuity",null,false],
["valgus",null,true],
["validation",null,false],
["value-added tax",null,false],
["vambrace",null,true],
["Van Allen belt",null,true],
["vaporescence",null,false],
["variolate",null,false],
["vaticinate",null,true],
["vegetable ivory",null,false],
["Velcro",null,false],
["velleity",null,true],
["Venezuela",null,false],
["venial",null,false],
["ventifact",null,false],
["ventilator",null,true],
["venue",null,false],
["verbigeration",null,false],
["verd antique","verde antique",false],
["verisimilitude",null,false],
["vermiculate",null,false],
["verruca",null,false],
["vesicate",null,false],
["vestigial",null,false],
["viaticum",null,false],
["vibraphone",null,false],
["Victoriana",null,true],
["videophone",null,false],
["vigoroso",null,false],
["vinasse",null,true],
["viper's bugloss",null,false],
["viridescent",null,false],
["vis major",null,false],
["viscid",null,false],
["visuospatial",null,false],
["viticulture",null,true],
["vitrescent",null,false],
["viviparous",null,true],
["volitive",null,false],
["volunteerism",null,false],
["volvulus",null,false],
["vulcanize",null,false],
["Wahhabism",null,false],
["wainwright",null,true],
["Wallachia","Walachia",false],
["Wampanoag",null,true],
["wapiti",null,true],
["watchword",null,true],
["Waterford",null,false],
["water-repellent",null,false],
["waxen",null,true],
["weatherize",null,false],
["webcam",null,false],
["Wesleyan",null,false],
["whelk",null,true],
["whimsicality",null,false],
["whipper-in",null,false],
["white paper",null,false],
["Wicca",null,false],
["Wilderness Road",null,false],
["willowware",null,false],
["wimple",null,false],
["Winesap",null,true],
["wombat",null,false],
["Woodstock",null,false],
["woofer",null,false],
["word processing",null,false],
["world-shaking",null,false],
["wraith",null,true],
["wrasse",null,false],
["Xanadu",null,true],
["xenogamy",null,false],
["xenophile",null,false],
["xeroderma pigmentosum",null,false],
["x-ray astronomy",null,false],
["xyster",null,true],
["yapok",null,true],
["yarmulke","yarmelke",false],
["yearling",null,true],
["Yemen",null,true],
["yersiniosis",null,true],
["youngberry",null,false],
["youth hostel",null,false],
["yowl",null,false],
["yurt",null,true],
["Z score",null,false],
["Zapata mustache",null,false],
["zapateado",null,false],
["zebu",null,true],
["zero hour",null,false],
["Zimbabwe",null,false],
["zinnia","Zinnia",true],
["zootomy",null,false],
["Zululand",null,true],
["zwieback",null,true],
["zygomatic bone",null,false]
];

// Common prefixes with meanings for analysis
const PREFIXES = {
  "a-": "not, without",
  "ab-": "away from",
  "ad-": "toward, to",
  "aero-": "air",
  "agro-": "field, agriculture",
  "alpha-": "first",
  "an-": "not, without",
  "ana-": "up, back, again",
  "ante-": "before",
  "anti-": "against, opposite",
  "auto-": "self",
  "bi-": "two",
  "bio-": "life",
  "cata-": "down",
  "centi-": "hundred",
  "circum-": "around",
  "co-": "together, with",
  "com-": "together, with",
  "con-": "together, with",
  "contra-": "against",
  "counter-": "against",
  "de-": "down, from, reverse",
  "deca-": "ten",
  "demi-": "half",
  "di-": "two",
  "dia-": "through, across",
  "dis-": "not, apart",
  "dys-": "bad, difficult",
  "eco-": "environment",
  "em-": "in, into",
  "en-": "in, into, cause",
  "endo-": "within",
  "epi-": "upon, above",
  "equi-": "equal",
  "eu-": "good, well",
  "ex-": "out of, former",
  "exo-": "outside",
  "extra-": "beyond",
  "fore-": "before, front",
  "geo-": "earth",
  "hemi-": "half",
  "hetero-": "different",
  "homo-": "same",
  "hydro-": "water",
  "hyper-": "over, excessive",
  "hypo-": "under, below",
  "il-": "not",
  "im-": "not, into",
  "in-": "not, into",
  "infra-": "below",
  "inter-": "between, among",
  "intra-": "within",
  "ir-": "not",
  "iso-": "equal",
  "macro-": "large",
  "mal-": "bad",
  "mega-": "large, great",
  "meta-": "beyond, change",
  "micro-": "small",
  "mid-": "middle",
  "milli-": "thousand",
  "mini-": "small",
  "mis-": "wrong, bad",
  "mono-": "one, single",
  "multi-": "many",
  "neo-": "new",
  "neuro-": "nerve",
  "non-": "not",
  "ob-": "against",
  "omni-": "all",
  "over-": "excessive",
  "paleo-": "ancient",
  "pan-": "all",
  "para-": "beside, beyond",
  "peri-": "around",
  "photo-": "light",
  "poly-": "many",
  "post-": "after",
  "pre-": "before",
  "pro-": "forward, in favor",
  "proto-": "first",
  "pseudo-": "false",
  "psycho-": "mind",
  "quadr-": "four",
  "quasi-": "seemingly",
  "re-": "again, back",
  "retro-": "backward",
  "sacro-": "sacred",
  "self-": "self",
  "semi-": "half, partly",
  "sub-": "under, below",
  "super-": "above, beyond",
  "supra-": "above",
  "sym-": "together",
  "syn-": "together",
  "tele-": "far, distant",
  "trans-": "across, beyond",
  "tri-": "three",
  "ultra-": "beyond, extreme",
  "un-": "not, reverse",
  "under-": "below, less",
  "uni-": "one",
  "vice-": "in place of"
};

// Common suffixes with meanings
const SUFFIXES = {
  "-able": "capable of being",
  "-ible": "capable of being",
  "-aceous": "resembling, relating to",
  "-acious": "having quality of",
  "-acity": "quality of",
  "-ade": "action, product",
  "-age": "action, state",
  "-al": "relating to",
  "-an": "relating to, native of",
  "-ance": "state, quality",
  "-ancy": "state, quality",
  "-ant": "one who, performing",
  "-ar": "relating to",
  "-arian": "one who, believer in",
  "-ary": "relating to, place for",
  "-ate": "having, cause to be",
  "-ation": "action, process",
  "-ative": "tending to",
  "-cide": "killing",
  "-cracy": "rule, government",
  "-crat": "ruler",
  "-dom": "state, realm",
  "-ean": "relating to",
  "-ectomy": "surgical removal",
  "-ee": "one who receives",
  "-emia": "blood condition",
  "-ence": "state, quality",
  "-ency": "state, quality",
  "-ent": "performing, causing",
  "-eous": "having nature of",
  "-er": "one who, more",
  "-ery": "place, practice",
  "-escence": "becoming",
  "-escent": "becoming",
  "-esque": "in the style of",
  "-ess": "female",
  "-est": "most",
  "-etic": "relating to",
  "-ette": "small, feminine",
  "-eur": "one who",
  "-ful": "full of",
  "-fy": "make, cause",
  "-gamy": "marriage",
  "-genic": "producing",
  "-geny": "origin, production",
  "-gon": "angle",
  "-gram": "written, drawn",
  "-graph": "writing, instrument",
  "-graphy": "writing, description",
  "-ia": "condition, region",
  "-ial": "relating to",
  "-ian": "relating to, one who",
  "-iasis": "disease condition",
  "-iatric": "medical treatment",
  "-ible": "capable of",
  "-ic": "relating to",
  "-ical": "relating to",
  "-ician": "specialist",
  "-ics": "science, study",
  "-id": "having quality of",
  "-ify": "make, cause to be",
  "-ile": "capable of, relating to",
  "-ine": "relating to, resembling",
  "-ion": "action, condition",
  "-ious": "having quality of",
  "-ism": "doctrine, practice",
  "-ist": "one who practices",
  "-istic": "relating to",
  "-ite": "native, follower",
  "-itis": "inflammation",
  "-itude": "state, quality",
  "-ity": "state, quality",
  "-ive": "tending to, having nature of",
  "-ization": "process of making",
  "-ize": "make, cause to be",
  "-kinesis": "movement",
  "-less": "without",
  "-like": "resembling",
  "-ling": "small, young",
  "-logy": "study of",
  "-ly": "in manner of",
  "-mania": "obsession",
  "-ment": "action, result",
  "-meter": "measuring device",
  "-metry": "measurement",
  "-morph": "form, shape",
  "-ness": "state, quality",
  "-nomy": "system of laws",
  "-oid": "resembling",
  "-ology": "study of",
  "-oma": "tumor, mass",
  "-opia": "vision condition",
  "-or": "one who",
  "-ory": "place for, relating to",
  "-osis": "condition, process",
  "-ous": "full of, having",
  "-pathy": "feeling, disease",
  "-phage": "eating",
  "-phagy": "eating",
  "-phile": "loving",
  "-philia": "love of",
  "-phobia": "fear of",
  "-phone": "sound",
  "-phyte": "plant",
  "-plasm": "formed substance",
  "-plasty": "surgical repair",
  "-pod": "foot",
  "-scope": "viewing instrument",
  "-scopy": "viewing",
  "-ship": "state, office",
  "-sis": "condition, process",
  "-some": "characterized by",
  "-stasis": "standing, stopping",
  "-tion": "action, state",
  "-tomy": "cutting",
  "-tude": "state, quality",
  "-ular": "relating to",
  "-ulent": "full of",
  "-ure": "action, process",
  "-ward": "direction",
  "-wise": "manner",
  "-y": "characterized by"
};

// PRACTICE_TESTS and analyzeWord() are defined in reference-data.js
